# lsmod | grep mlx
mlx5_core            2203648  0
mlxfw                  32768  1 mlx5_core
mlxdevm               176128  1 mlx5_core
mlx_compat             69632  8 ib_ipoib,mlxdevm,mlxfw,ib_umad,ib_core,ib_uverbs,ib_cm,mlx5_core
psample                20480  1 mlx5_core
tls                   114688  1 mlx5_core

# modinfo mlx5_ib
filename:       /lib/modules/5.15.0-1087-azure/kernel/drivers/infiniband/hw/mlx5/mlx5_ib.ko
license:        Dual BSD/GPL
description:    Mellanox 5th generation network adapters (ConnectX series) IB driver
author:         Eli Cohen <eli@mellanox.com>
srcversion:     ACF3DC84F2E17FED5AC00D7
alias:          auxiliary:mlx5_core.rdma
alias:          auxiliary:mlx5_core.multiport
alias:          auxiliary:mlx5_core.rdma-rep
depends:        mlx5_core,ib_core,ib_uverbs
retpoline:      Y
intree:         Y
name:           mlx5_ib
vermagic:       5.15.0-1087-azure SMP mod_unload modversions
sig_id:         PKCS#7
signer:         Build time autogenerated kernel key
sig_key:        37:D1:D0:7E:E6:01:12:9D:44:3B:F6:3A:03:58:05:63:92:E9:48:10
sig_hashalgo:   sha512
signature:      77:8B:08:E2:2F:F4:16:05:A8:97:0D:E0:BE:07:1A:FB:1C:C3:AA:D0:
		FF:EA:8C:5C:16:AE:33:04:EE:2A:D3:F7:B2:63:8B:0B:B4:74:DE:AF:
		77:2A:EF:93:65:A2:16:63:AC:4E:DD:FD:57:39:A8:91:65:47:09:8D:
		84:7F:5F:06:2D:2D:64:DA:F4:2C:77:E3:AF:04:E4:8F:C7:D8:4D:A6:
		89:0B:21:D0:24:CF:64:AF:42:BF:1E:A5:43:AC:47:DB:6D:7D:BF:77:
		D9:E7:B4:35:A9:3B:CB:79:31:B3:EC:7F:5F:4D:F1:9E:0E:E4:D8:18:
		24:4C:F8:F5:5A:3B:5F:F8:99:21:62:F4:51:F6:30:EC:4B:7C:37:D2:
		88:C3:2A:4A:97:63:EA:AE:35:61:C2:5E:02:EF:C3:79:50:BD:66:CA:
		46:AA:E5:FB:2D:F9:57:06:15:F1:09:A2:C1:63:4A:9B:CC:C2:D1:0B:
		33:2F:6C:88:B2:67:5F:AA:A7:0D:A4:FB:C1:1E:82:78:1D:8B:A5:34:
		8A:C0:32:FE:95:43:6F:56:A1:64:A6:27:27:D1:25:2C:D4:61:EE:91:
		4C:57:E7:D2:89:A8:97:EB:CB:86:37:1F:93:99:79:92:4E:40:46:47:
		40:22:2C:B6:EA:DC:6C:D7:C4:07:24:86:A8:4F:E5:F3:73:52:76:C0:
		4E:96:C4:F7:8F:76:47:66:CD:35:05:FE:C2:7C:26:61:69:17:8F:E5:
		C2:77:BB:41:A5:7A:30:77:A5:6B:B4:DD:92:F6:89:37:ED:0F:0E:5C:
		AD:C8:F1:58:B5:18:5A:33:CA:A4:AB:BD:4D:EB:97:B2:7B:B4:F2:3A:
		74:10:B9:A2:67:98:D3:09:51:8A:87:E9:4E:5F:AE:71:7D:7D:C8:E7:
		22:27:EF:55:C0:45:2C:F1:34:AE:FF:61:D3:06:5E:70:65:29:72:75:
		5C:15:4A:05:89:FB:41:64:D2:D4:27:25:41:20:11:F8:87:71:E2:A4:
		20:8B:C2:0B:51:92:01:D7:FE:E5:0F:FB:D1:0F:12:0C:72:4C:63:4D:
		ED:11:34:7E:FB:34:D0:3F:87:62:B4:48:62:F8:10:30:E1:22:AC:B1:
		B8:3E:89:59:83:F5:2F:99:00:29:F8:87:A8:46:D2:85:9E:8A:5A:0D:
		A8:AC:FE:34:F4:46:26:53:8C:6F:0D:FB:A9:2E:CA:30:D8:78:3F:D5:
		96:73:FD:25:45:AE:1D:71:B2:E4:A4:60:B2:08:43:DF:E2:36:FD:5C:
		54:19:31:AC:FD:A9:38:F3:FE:6D:21:9E:24:84:B7:12:23:84:F1:D1:
		2E:4B:1B:8B:9A:14:0A:82:41:EA:10:7D

# modinfo mlx5_core
filename:       /lib/modules/5.15.0-1087-azure/kernel/drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.ko
license:        Dual BSD/GPL
description:    Mellanox 5th generation network adapters (ConnectX series) core driver
author:         Eli Cohen <eli@mellanox.com>
srcversion:     5C665939D32BB564858EA35
alias:          auxiliary:mlx5_core.eth
alias:          pci:v000015B3d0000A2DFsv*sd*bc*sc*i*
alias:          pci:v000015B3d0000A2DCsv*sd*bc*sc*i*
alias:          pci:v000015B3d0000A2D6sv*sd*bc*sc*i*
alias:          pci:v000015B3d0000A2D3sv*sd*bc*sc*i*
alias:          pci:v000015B3d0000A2D2sv*sd*bc*sc*i*
alias:          pci:v000015B3d00001023sv*sd*bc*sc*i*
alias:          pci:v000015B3d00001021sv*sd*bc*sc*i*
alias:          pci:v000015B3d0000101Fsv*sd*bc*sc*i*
alias:          pci:v000015B3d0000101Esv*sd*bc*sc*i*
alias:          pci:v000015B3d0000101Dsv*sd*bc*sc*i*
alias:          pci:v000015B3d0000101Csv*sd*bc*sc*i*
alias:          pci:v000015B3d0000101Bsv*sd*bc*sc*i*
alias:          pci:v000015B3d0000101Asv*sd*bc*sc*i*
alias:          pci:v000015B3d00001019sv*sd*bc*sc*i*
alias:          pci:v000015B3d00001018sv*sd*bc*sc*i*
alias:          pci:v000015B3d00001017sv*sd*bc*sc*i*
alias:          pci:v000015B3d00001016sv*sd*bc*sc*i*
alias:          pci:v000015B3d00001015sv*sd*bc*sc*i*
alias:          pci:v000015B3d00001014sv*sd*bc*sc*i*
alias:          pci:v000015B3d00001013sv*sd*bc*sc*i*
alias:          pci:v000015B3d00001012sv*sd*bc*sc*i*
alias:          pci:v000015B3d00001011sv*sd*bc*sc*i*
alias:          auxiliary:mlx5_core.eth-rep
alias:          auxiliary:mlx5_core.sf
depends:        tls,mlxfw,psample
retpoline:      Y
intree:         Y
name:           mlx5_core
vermagic:       5.15.0-1087-azure SMP mod_unload modversions
sig_id:         PKCS#7
signer:         Build time autogenerated kernel key
sig_key:        37:D1:D0:7E:E6:01:12:9D:44:3B:F6:3A:03:58:05:63:92:E9:48:10
sig_hashalgo:   sha512
signature:      62:D6:95:A9:42:08:7B:07:F8:1A:A2:50:6F:5A:0A:DB:A5:AB:4D:29:
		93:E9:11:B6:11:17:C5:A9:A4:59:A0:1B:54:14:50:B6:3D:DE:41:DE:
		76:B9:1F:B8:2F:31:AD:F0:A8:E0:CF:D0:9B:DF:03:9C:BA:94:26:F8:
		CE:55:12:7D:E5:47:64:3C:99:F6:18:A4:EA:E9:D3:BE:39:62:1C:C0:
		C8:39:88:91:E1:5C:CB:67:9F:72:7A:32:5B:28:0E:24:E2:FF:59:B4:
		D4:91:DB:A8:0F:3F:3D:68:44:13:FA:A9:CD:00:40:B4:3D:17:B1:B9:
		20:C2:C5:CD:64:9A:D3:A8:B2:79:58:E3:8B:4A:C6:A7:7F:EF:36:EF:
		97:65:EC:57:1E:76:69:9B:8C:41:8A:AB:B7:89:A0:62:C6:DD:53:16:
		21:77:E5:DB:28:3B:2A:3E:3B:53:CD:C4:86:55:1F:EA:10:20:0D:B0:
		F7:BE:4C:87:9B:02:C3:93:67:AA:BC:0D:E1:8D:12:8F:46:5C:EC:0C:
		1F:5E:55:03:8F:27:C9:E5:1A:79:43:BF:BA:26:3E:21:0C:48:02:5F:
		95:02:8B:DF:5B:BD:09:91:52:FF:C2:45:AE:18:83:88:51:A9:74:3B:
		07:FE:AF:2D:17:2E:99:CB:09:60:62:69:B4:01:13:A6:C5:7E:35:75:
		F5:1A:42:96:3E:9C:CB:A3:9A:42:2F:E2:FC:5C:DD:00:1C:9E:11:79:
		2B:C3:6A:45:D6:C4:FA:32:52:2B:4C:2F:CA:9E:EC:77:50:AA:83:A3:
		71:57:B5:B9:24:13:2A:28:69:AC:1E:57:FD:76:8F:A0:54:38:93:59:
		15:8D:C4:E4:3C:01:6B:B1:34:92:AE:3D:1B:64:38:75:7E:B2:F5:88:
		9D:AB:7B:64:09:11:2D:E6:8D:C8:47:D3:96:86:30:74:C7:3C:31:46:
		8F:77:F8:B2:DD:CC:8F:69:F2:0E:21:A1:A3:90:94:99:4E:3A:AF:6C:
		52:30:9E:B2:0F:F4:0B:97:49:94:8C:1E:16:10:7F:6B:7E:8F:59:E9:
		D3:35:FD:AD:DF:EF:AC:E5:4B:FF:10:88:61:A2:F2:FB:EA:7B:8B:B8:
		FB:07:8E:41:E4:06:DA:73:45:2C:45:FB:40:6C:2C:95:42:9A:DB:DB:
		0C:40:4B:27:0E:3B:89:07:16:EC:9C:30:C2:57:5E:85:4F:87:78:F5:
		E5:E9:CF:48:96:5F:C7:49:7C:F0:66:D8:07:C2:8F:03:DE:D3:C0:E4:
		4E:D9:B1:74:30:F0:DF:0D:C1:52:38:72:4A:B0:6C:AF:BB:BB:91:25:
		42:58:9B:AC:7E:56:18:41:AE:67:92:19
parm:           debug_mask:debug mask: 1 = dump cmd data, 2 = dump cmd exec time, 3 = both. Default=0 (uint)
parm:           prof_sel:profile selector. Valid range 0 - 2 (uint)

# modprobe mlx5_ib
modprobe: ERROR: could not insert 'mlx5_ib': Invalid argument

# dmesg
[ 5064.203310] mlx5_ib: disagrees about version of symbol mlx5_eswitch_add_send_to_vport_rule
[ 5064.203316] mlx5_ib: Unknown symbol mlx5_eswitch_add_send_to_vport_rule (err -22)
[ 5064.203335] mlx5_ib: disagrees about version of symbol mlx5_modify_header_alloc
[ 5064.203337] mlx5_ib: Unknown symbol mlx5_modify_header_alloc (err -22)
[ 5064.203347] mlx5_ib: disagrees about version of symbol mlx5_dm_sw_icm_dealloc
[ 5064.203349] mlx5_ib: Unknown symbol mlx5_dm_sw_icm_dealloc (err -22)
[ 5064.203366] mlx5_ib: disagrees about version of symbol ib_umem_release
[ 5064.203367] mlx5_ib: Unknown symbol ib_umem_release (err -22)
[ 5064.203377] mlx5_ib: disagrees about version of symbol mlx5_db_free
[ 5064.203378] mlx5_ib: Unknown symbol mlx5_db_free (err -22)
[ 5064.203398] mlx5_ib: disagrees about version of symbol mlx5_core_destroy_mkey
[ 5064.203399] mlx5_ib: Unknown symbol mlx5_core_destroy_mkey (err -22)
[ 5064.203409] mlx5_ib: disagrees about version of symbol mlx5_eswitch_mode
[ 5064.203410] mlx5_ib: Unknown symbol mlx5_eswitch_mode (err -22)
[ 5064.203455] mlx5_ib: disagrees about version of symbol mlx5_rl_add_rate_raw
[ 5064.203456] mlx5_ib: Unknown symbol mlx5_rl_add_rate_raw (err -22)
[ 5064.203465] mlx5_ib: disagrees about version of symbol mlx5_lag_query_cong_counters
[ 5064.203466] mlx5_ib: Unknown symbol mlx5_lag_query_cong_counters (err -22)
[ 5064.203478] mlx5_ib: disagrees about version of symbol uverbs_get_flags32
[ 5064.203479] mlx5_ib: Unknown symbol uverbs_get_flags32 (err -22)
[ 5064.203488] mlx5_ib: disagrees about version of symbol mlx5_rsc_dump_cmd_create
[ 5064.203489] mlx5_ib: Unknown symbol mlx5_rsc_dump_cmd_create (err -22)
[ 5064.203498] mlx5_ib: disagrees about version of symbol uverbs_idr_class
[ 5064.203499] mlx5_ib: Unknown symbol uverbs_idr_class (err -22)
[ 5064.203515] mlx5_ib: disagrees about version of symbol mlx5_core_destroy_psv
[ 5064.203517] mlx5_ib: Unknown symbol mlx5_core_destroy_psv (err -22)
[ 5064.203551] mlx5_ib: disagrees about version of symbol mlx5_eq_enable
[ 5064.203552] mlx5_ib: Unknown symbol mlx5_eq_enable (err -22)
[ 5064.203564] mlx5_ib: disagrees about version of symbol rdma_read_gid_l2_fields
[ 5064.203565] mlx5_ib: Unknown symbol rdma_read_gid_l2_fields (err -22)
[ 5064.203582] mlx5_ib: disagrees about version of symbol __ib_alloc_pd
[ 5064.203583] mlx5_ib: Unknown symbol __ib_alloc_pd (err -22)
[ 5064.203622] mlx5_ib: disagrees about version of symbol mlx5_query_nic_vport_qkey_viol_cntr
[ 5064.203624] mlx5_ib: Unknown symbol mlx5_query_nic_vport_qkey_viol_cntr (err -22)
[ 5064.203633] mlx5_ib: disagrees about version of symbol ib_modify_qp_is_ok
[ 5064.203635] mlx5_ib: Unknown symbol ib_modify_qp_is_ok (err -22)
[ 5064.203649] mlx5_ib: disagrees about version of symbol mlx5_nic_vport_update_local_lb
[ 5064.203651] mlx5_ib: Unknown symbol mlx5_nic_vport_update_local_lb (err -22)
[ 5064.203681] mlx5_ib: disagrees about version of symbol uverbs_uobject_fd_release
[ 5064.203682] mlx5_ib: Unknown symbol uverbs_uobject_fd_release (err -22)
[ 5064.203699] mlx5_ib: disagrees about version of symbol mlx5_core_create_psv
[ 5064.203700] mlx5_ib: Unknown symbol mlx5_core_create_psv (err -22)
[ 5064.203709] mlx5_ib: disagrees about version of symbol ib_umem_find_best_pgsz
[ 5064.203711] mlx5_ib: Unknown symbol ib_umem_find_best_pgsz (err -22)
[ 5064.203720] mlx5_ib: disagrees about version of symbol mlx5_core_modify_hca_vport_context
[ 5064.203721] mlx5_ib: Unknown symbol mlx5_core_modify_hca_vport_context (err -22)
[ 5064.203734] mlx5_ib: disagrees about version of symbol mlx5_rl_add_rate
[ 5064.203735] mlx5_ib: Unknown symbol mlx5_rl_add_rate (err -22)
[ 5064.203743] mlx5_ib: disagrees about version of symbol mlx5_eq_update_ci
[ 5064.203745] mlx5_ib: Unknown symbol mlx5_eq_update_ci (err -22)
[ 5064.203753] mlx5_ib: disagrees about version of symbol mlx5_create_auto_grouped_flow_table
[ 5064.203755] mlx5_ib: Unknown symbol mlx5_create_auto_grouped_flow_table (err -22)
[ 5064.203763] mlx5_ib: disagrees about version of symbol mlx5_core_create_mkey
[ 5064.203764] mlx5_ib: Unknown symbol mlx5_core_create_mkey (err -22)
[ 5064.203778] mlx5_ib: disagrees about version of symbol mlx5_debug_qp_add
[ 5064.203779] mlx5_ib: Unknown symbol mlx5_debug_qp_add (err -22)
[ 5064.203788] mlx5_ib: disagrees about version of symbol ib_sg_to_pages
[ 5064.203790] mlx5_ib: Unknown symbol ib_sg_to_pages (err -22)
[ 5064.203816] mlx5_ib: disagrees about version of symbol mlx5_fc_create
[ 5064.203817] mlx5_ib: Unknown symbol mlx5_fc_create (err -22)
[ 5064.203825] mlx5_ib: disagrees about version of symbol mlx5_core_create_rqt
[ 5064.203826] mlx5_ib: Unknown symbol mlx5_core_create_rqt (err -22)
[ 5064.203835] mlx5_ib: disagrees about version of symbol mlx5_query_hca_vport_node_guid
[ 5064.203836] mlx5_ib: Unknown symbol mlx5_query_hca_vport_node_guid (err -22)
[ 5064.203844] mlx5_ib: disagrees about version of symbol mlx5_core_query_vendor_id
[ 5064.203846] mlx5_ib: Unknown symbol mlx5_core_query_vendor_id (err -22)
[ 5064.203853] mlx5_ib: disagrees about version of symbol mlx5_modify_header_dealloc
[ 5064.203854] mlx5_ib: Unknown symbol mlx5_modify_header_dealloc (err -22)
[ 5064.203868] mlx5_ib: disagrees about version of symbol ib_umem_odp_alloc_child
[ 5064.203870] mlx5_ib: Unknown symbol ib_umem_odp_alloc_child (err -22)
[ 5064.203906] mlx5_ib: Unknown symbol mlx5_db_alloc (err -2)
[ 5064.203919] mlx5_ib: disagrees about version of symbol ib_process_cq_direct
[ 5064.203921] mlx5_ib: Unknown symbol ib_process_cq_direct (err -22)
[ 5064.203950] mlx5_ib: disagrees about version of symbol uverbs_finalize_uobj_create
[ 5064.203952] mlx5_ib: Unknown symbol uverbs_finalize_uobj_create (err -22)
[ 5064.203966] mlx5_ib: disagrees about version of symbol mlx5_eswitch_get_encap_mode
[ 5064.203968] mlx5_ib: Unknown symbol mlx5_eswitch_get_encap_mode (err -22)
[ 5064.203975] mlx5_ib: disagrees about version of symbol mlx5_rsc_dump_next
[ 5064.203977] mlx5_ib: Unknown symbol mlx5_rsc_dump_next (err -22)
[ 5064.203986] mlx5_ib: disagrees about version of symbol ib_query_qp
[ 5064.203987] mlx5_ib: Unknown symbol ib_query_qp (err -22)
[ 5064.203997] mlx5_ib: disagrees about version of symbol _ib_alloc_device
[ 5064.203998] mlx5_ib: Unknown symbol _ib_alloc_device (err -22)
[ 5064.204022] mlx5_ib: disagrees about version of symbol flow_resources_alloc
[ 5064.204024] mlx5_ib: Unknown symbol flow_resources_alloc (err -22)
[ 5064.204045] mlx5_ib: disagrees about version of symbol mlx5_core_query_rq
[ 5064.204047] mlx5_ib: Unknown symbol mlx5_core_query_rq (err -22)
[ 5064.204058] mlx5_ib: disagrees about version of symbol mlx5_packet_reformat_dealloc
[ 5064.204060] mlx5_ib: Unknown symbol mlx5_packet_reformat_dealloc (err -22)
[ 5064.204079] mlx5_ib: disagrees about version of symbol ib_umem_odp_alloc_implicit
[ 5064.204081] mlx5_ib: Unknown symbol ib_umem_odp_alloc_implicit (err -22)
[ 5064.204094] mlx5_ib: disagrees about version of symbol ib_destroy_srq_user
[ 5064.204095] mlx5_ib: Unknown symbol ib_destroy_srq_user (err -22)
[ 5064.204108] mlx5_ib: disagrees about version of symbol ib_unregister_device
[ 5064.204110] mlx5_ib: Unknown symbol ib_unregister_device (err -22)
[ 5064.204118] mlx5_ib: disagrees about version of symbol ib_find_cached_pkey
[ 5064.204119] mlx5_ib: Unknown symbol ib_find_cached_pkey (err -22)
[ 5064.204143] mlx5_ib: disagrees about version of symbol mlx5_cmd_exec
[ 5064.204144] mlx5_ib: Unknown symbol mlx5_cmd_exec (err -22)
[ 5064.204151] mlx5_ib: disagrees about version of symbol mlx5_eq_get_eqe
[ 5064.204153] mlx5_ib: Unknown symbol mlx5_eq_get_eqe (err -22)
[ 5064.204173] mlx5_ib: disagrees about version of symbol mlx5_rdma_rn_get_params
[ 5064.204174] mlx5_ib: Unknown symbol mlx5_rdma_rn_get_params (err -22)
[ 5064.204186] mlx5_ib: disagrees about version of symbol ib_register_device
[ 5064.204188] mlx5_ib: Unknown symbol ib_register_device (err -22)
[ 5064.204218] mlx5_ib: disagrees about version of symbol mlx5_debug_qp_remove
[ 5064.204220] mlx5_ib: Unknown symbol mlx5_debug_qp_remove (err -22)
[ 5064.204236] mlx5_ib: disagrees about version of symbol mlx5_eq_notifier_register
[ 5064.204238] mlx5_ib: Unknown symbol mlx5_eq_notifier_register (err -22)
[ 5064.204253] mlx5_ib: Unknown symbol mlx5_accel_esp_create_xfrm (err -2)
[ 5064.204264] mlx5_ib: disagrees about version of symbol mlx5_core_create_tis
[ 5064.204266] mlx5_ib: Unknown symbol mlx5_core_create_tis (err -22)
[ 5064.204273] mlx5_ib: disagrees about version of symbol mlx5_nic_vport_affiliate_multiport
[ 5064.204274] mlx5_ib: Unknown symbol mlx5_nic_vport_affiliate_multiport (err -22)
[ 5064.204293] mlx5_ib: disagrees about version of symbol mlx5_cmd_create_vport_lag
[ 5064.204295] mlx5_ib: Unknown symbol mlx5_cmd_create_vport_lag (err -22)
[ 5064.204305] mlx5_ib: disagrees about version of symbol mlx5_query_min_inline
[ 5064.204307] mlx5_ib: Unknown symbol mlx5_query_min_inline (err -22)
[ 5064.204323] mlx5_ib: disagrees about version of symbol mlx5_core_create_rq
[ 5064.204324] mlx5_ib: Unknown symbol mlx5_core_create_rq (err -22)
[ 5064.204331] mlx5_ib: disagrees about version of symbol mlx5_eswitch_get_vport_metadata_for_match
[ 5064.204333] mlx5_ib: Unknown symbol mlx5_eswitch_get_vport_metadata_for_match (err -22)
[ 5064.204347] mlx5_ib: disagrees about version of symbol mlx5_packet_reformat_alloc
[ 5064.204349] mlx5_ib: Unknown symbol mlx5_packet_reformat_alloc (err -22)
[ 5064.204361] mlx5_ib: disagrees about version of symbol ib_create_srq_user
[ 5064.204362] mlx5_ib: Unknown symbol ib_create_srq_user (err -22)
[ 5064.204370] mlx5_ib: disagrees about version of symbol rdma_user_mmap_entry_remove
[ 5064.204372] mlx5_ib: Unknown symbol rdma_user_mmap_entry_remove (err -22)
[ 5064.204379] mlx5_ib: disagrees about version of symbol _uverbs_get_const_unsigned
[ 5064.204380] mlx5_ib: Unknown symbol _uverbs_get_const_unsigned (err -22)
[ 5064.204388] mlx5_ib: disagrees about version of symbol ib_dispatch_event
[ 5064.204389] mlx5_ib: Unknown symbol ib_dispatch_event (err -22)
[ 5064.204404] mlx5_ib: Unknown symbol mlx5_accel_ipsec_device_caps (err -2)
[ 5064.204415] mlx5_ib: disagrees about version of symbol mlx5_lag_is_shared_fdb
[ 5064.204419] mlx5_ib: Unknown symbol mlx5_lag_is_shared_fdb (err -22)
[ 5064.204427] mlx5_ib: disagrees about version of symbol ib_umem_odp_release
[ 5064.204428] mlx5_ib: Unknown symbol ib_umem_odp_release (err -22)
[ 5064.204439] mlx5_ib: disagrees about version of symbol mlx5_query_nic_vport_system_image_guid
[ 5064.204440] mlx5_ib: Unknown symbol mlx5_query_nic_vport_system_image_guid (err -22)
[ 5064.204447] mlx5_ib: disagrees about version of symbol mlx5_eswitch_unregister_vport_reps
[ 5064.204449] mlx5_ib: Unknown symbol mlx5_eswitch_unregister_vport_reps (err -22)
[ 5064.204460] mlx5_ib: disagrees about version of symbol mlx5_notifier_register
[ 5064.204461] mlx5_ib: Unknown symbol mlx5_notifier_register (err -22)
[ 5064.204467] mlx5_ib: disagrees about version of symbol mlx5_core_create_cq
[ 5064.204469] mlx5_ib: Unknown symbol mlx5_core_create_cq (err -22)
[ 5064.204475] mlx5_ib: disagrees about version of symbol mlx5_dm_sw_icm_alloc
[ 5064.204477] mlx5_ib: Unknown symbol mlx5_dm_sw_icm_alloc (err -22)
[ 5064.204495] mlx5_ib: Unknown symbol mlx5_lag_get_roce_netdev (err -2)
[ 5064.204501] mlx5_ib: disagrees about version of symbol mlx5_add_flow_rules
[ 5064.204503] mlx5_ib: Unknown symbol mlx5_add_flow_rules (err -22)
[ 5064.204513] mlx5_ib: disagrees about version of symbol mlx5_destroy_flow_table
[ 5064.204515] mlx5_ib: Unknown symbol mlx5_destroy_flow_table (err -22)
[ 5064.204521] mlx5_ib: disagrees about version of symbol mlx5_eswitch_uplink_get_proto_dev
[ 5064.204522] mlx5_ib: Unknown symbol mlx5_eswitch_uplink_get_proto_dev (err -22)
[ 5064.204528] mlx5_ib: disagrees about version of symbol mlx5_get_flow_namespace
[ 5064.204530] mlx5_ib: Unknown symbol mlx5_get_flow_namespace (err -22)
[ 5064.204548] mlx5_ib: Unknown symbol mlx5_comp_vectors_count (err -2)
[ 5064.204567] mlx5_ib: disagrees about version of symbol ib_umem_odp_get
[ 5064.204568] mlx5_ib: Unknown symbol ib_umem_odp_get (err -22)
[ 5064.204578] mlx5_ib: disagrees about version of symbol mlx5_query_port_ptys
[ 5064.204580] mlx5_ib: Unknown symbol mlx5_query_port_ptys (err -22)
[ 5064.204598] mlx5_ib: disagrees about version of symbol mlx5_cmd_init_async_ctx
[ 5064.204599] mlx5_ib: Unknown symbol mlx5_cmd_init_async_ctx (err -22)
[ 5064.204605] mlx5_ib: disagrees about version of symbol mlx5_put_uars_page
[ 5064.204607] mlx5_ib: Unknown symbol mlx5_put_uars_page (err -22)
[ 5064.204613] mlx5_ib: disagrees about version of symbol mlx5_eq_create_generic
[ 5064.204614] mlx5_ib: Unknown symbol mlx5_eq_create_generic (err -22)
[ 5064.204620] mlx5_ib: disagrees about version of symbol mlx5_lag_get_slave_port
[ 5064.204622] mlx5_ib: Unknown symbol mlx5_lag_get_slave_port (err -22)
[ 5064.204631] mlx5_ib: disagrees about version of symbol mlx5_get_uars_page
[ 5064.204633] mlx5_ib: Unknown symbol mlx5_get_uars_page (err -22)
[ 5064.204639] mlx5_ib: disagrees about version of symbol ib_umem_dmabuf_map_pages
[ 5064.204641] mlx5_ib: Unknown symbol ib_umem_dmabuf_map_pages (err -22)
[ 5064.204647] mlx5_ib: disagrees about version of symbol mlx5_query_ib_port_oper
[ 5064.204648] mlx5_ib: Unknown symbol mlx5_query_ib_port_oper (err -22)
[ 5064.204655] mlx5_ib: disagrees about version of symbol ib_query_port
[ 5064.204657] mlx5_ib: Unknown symbol ib_query_port (err -22)
[ 5064.204664] mlx5_ib: disagrees about version of symbol __ib_alloc_cq
[ 5064.204665] mlx5_ib: Unknown symbol __ib_alloc_cq (err -22)
[ 5064.204671] mlx5_ib: disagrees about version of symbol mlx5_query_nic_vport_node_guid
[ 5064.204673] mlx5_ib: Unknown symbol mlx5_query_nic_vport_node_guid (err -22)
[ 5064.204690] mlx5_ib: disagrees about version of symbol mlx5_set_port_caps
[ 5064.204691] mlx5_ib: Unknown symbol mlx5_set_port_caps (err -22)
[ 5064.204698] mlx5_ib: disagrees about version of symbol rdma_user_mmap_entry_get_pgoff
[ 5064.204700] mlx5_ib: Unknown symbol rdma_user_mmap_entry_get_pgoff (err -22)
[ 5064.204705] mlx5_ib: disagrees about version of symbol mlx5_del_flow_rules
[ 5064.204707] mlx5_ib: Unknown symbol mlx5_del_flow_rules (err -22)
[ 5064.204713] mlx5_ib: disagrees about version of symbol ib_umem_odp_unmap_dma_pages
[ 5064.204715] mlx5_ib: Unknown symbol ib_umem_odp_unmap_dma_pages (err -22)
[ 5064.204725] mlx5_ib: disagrees about version of symbol mlx5_core_modify_sq
[ 5064.204726] mlx5_ib: Unknown symbol mlx5_core_modify_sq (err -22)
[ 5064.204739] mlx5_ib: disagrees about version of symbol ib_umem_dmabuf_get
[ 5064.204741] mlx5_ib: Unknown symbol ib_umem_dmabuf_get (err -22)
[ 5064.204747] mlx5_ib: disagrees about version of symbol mlx5_query_hca_vport_system_image_guid
[ 5064.204748] mlx5_ib: Unknown symbol mlx5_query_hca_vport_system_image_guid (err -22)
[ 5064.204754] mlx5_ib: disagrees about version of symbol mlx5_core_query_sq_state
[ 5064.204756] mlx5_ib: Unknown symbol mlx5_core_query_sq_state (err -22)
[ 5064.204766] mlx5_ib: disagrees about version of symbol ib_umem_stop_invalidation_notifier
[ 5064.204767] mlx5_ib: Unknown symbol ib_umem_stop_invalidation_notifier (err -22)
[ 5064.204773] mlx5_ib: disagrees about version of symbol mlx5_core_query_vport_counter
[ 5064.204775] mlx5_ib: Unknown symbol mlx5_core_query_vport_counter (err -22)
[ 5064.204781] mlx5_ib: disagrees about version of symbol ib_uverbs_get_ucontext_file
[ 5064.204782] mlx5_ib: Unknown symbol ib_uverbs_get_ucontext_file (err -22)
[ 5064.204795] mlx5_ib: disagrees about version of symbol __ib_create_cq
[ 5064.204797] mlx5_ib: Unknown symbol __ib_create_cq (err -22)
[ 5064.204805] mlx5_ib: disagrees about version of symbol mlx5_query_port_max_mtu
[ 5064.204807] mlx5_ib: Unknown symbol mlx5_query_port_max_mtu (err -22)
[ 5064.204813] mlx5_ib: disagrees about version of symbol ib_destroy_qp_user
[ 5064.204815] mlx5_ib: Unknown symbol ib_destroy_qp_user (err -22)
[ 5064.204821] mlx5_ib: disagrees about version of symbol mlx5_query_hca_vport_gid
[ 5064.204822] mlx5_ib: Unknown symbol mlx5_query_hca_vport_gid (err -22)
[ 5064.204828] mlx5_ib: disagrees about version of symbol mlx5_frag_buf_free
[ 5064.204829] mlx5_ib: Unknown symbol mlx5_frag_buf_free (err -22)
[ 5064.204835] mlx5_ib: disagrees about version of symbol mlx5_nic_vport_disable_roce
[ 5064.204836] mlx5_ib: Unknown symbol mlx5_nic_vport_disable_roce (err -22)
[ 5064.204842] mlx5_ib: disagrees about version of symbol uverbs_fd_class
[ 5064.204844] mlx5_ib: Unknown symbol uverbs_fd_class (err -22)
[ 5064.204854] mlx5_ib: disagrees about version of symbol mlx5_notifier_unregister
[ 5064.204856] mlx5_ib: Unknown symbol mlx5_notifier_unregister (err -22)
[ 5064.204867] mlx5_ib: disagrees about version of symbol mlx5_create_lag_demux_flow_table
[ 5064.204868] mlx5_ib: Unknown symbol mlx5_create_lag_demux_flow_table (err -22)
[ 5064.204883] mlx5_ib: Unknown symbol mlx5_accel_esp_modify_xfrm (err -2)
[ 5064.204889] mlx5_ib: disagrees about version of symbol mlx5_cmd_exec_cb
[ 5064.204890] mlx5_ib: Unknown symbol mlx5_cmd_exec_cb (err -22)
[ 5064.204901] mlx5_ib: disagrees about version of symbol mlx5_rl_remove_rate
[ 5064.204903] mlx5_ib: Unknown symbol mlx5_rl_remove_rate (err -22)
[ 5064.204921] mlx5_ib: disagrees about version of symbol mlx5_eswitch_register_vport_reps
[ 5064.204923] mlx5_ib: Unknown symbol mlx5_eswitch_register_vport_reps (err -22)
[ 5064.204933] mlx5_ib: disagrees about version of symbol mlx5_core_modify_cq
[ 5064.204934] mlx5_ib: Unknown symbol mlx5_core_modify_cq (err -22)
[ 5064.204940] mlx5_ib: disagrees about version of symbol ib_umem_activate_invalidation_notifier
[ 5064.204942] mlx5_ib: Unknown symbol ib_umem_activate_invalidation_notifier (err -22)
[ 5064.204947] mlx5_ib: disagrees about version of symbol mlx5_eswitch_vport_match_metadata_enabled
[ 5064.204948] mlx5_ib: Unknown symbol mlx5_eswitch_vport_match_metadata_enabled (err -22)
[ 5064.204954] mlx5_ib: disagrees about version of symbol ib_dealloc_device
[ 5064.204956] mlx5_ib: Unknown symbol ib_dealloc_device (err -22)
[ 5064.204961] mlx5_ib: disagrees about version of symbol mlx5_fc_query
[ 5064.204962] mlx5_ib: Unknown symbol mlx5_fc_query (err -22)
[ 5064.204968] mlx5_ib: disagrees about version of symbol ib_destroy_cq_user
[ 5064.204970] mlx5_ib: Unknown symbol ib_destroy_cq_user (err -22)
[ 5064.204976] mlx5_ib: disagrees about version of symbol rdma_user_mmap_io
[ 5064.204977] mlx5_ib: Unknown symbol rdma_user_mmap_io (err -22)
[ 5064.204991] mlx5_ib: disagrees about version of symbol ib_modify_qp
[ 5064.204993] mlx5_ib: Unknown symbol ib_modify_qp (err -22)
[ 5064.204998] mlx5_ib: disagrees about version of symbol mlx5_eswitch_get_core_dev
[ 5064.204999] mlx5_ib: Unknown symbol mlx5_eswitch_get_core_dev (err -22)
[ 5064.205015] mlx5_ib: disagrees about version of symbol rdma_user_mmap_entry_insert_range
[ 5064.205017] mlx5_ib: Unknown symbol rdma_user_mmap_entry_insert_range (err -22)
[ 5064.205038] mlx5_ib: disagrees about version of symbol ib_umem_dmabuf_unmap_pages
[ 5064.205040] mlx5_ib: Unknown symbol ib_umem_dmabuf_unmap_pages (err -22)
[ 5064.205045] mlx5_ib: disagrees about version of symbol ib_umem_get_peer
[ 5064.205046] mlx5_ib: Unknown symbol ib_umem_get_peer (err -22)
[ 5064.205055] mlx5_ib: disagrees about version of symbol mlx5_eswitch_get_proto_dev
[ 5064.205056] mlx5_ib: Unknown symbol mlx5_eswitch_get_proto_dev (err -22)
[ 5064.205068] mlx5_ib: disagrees about version of symbol uverbs_copy_to_struct_or_zero
[ 5064.205069] mlx5_ib: Unknown symbol uverbs_copy_to_struct_or_zero (err -22)
[ 5064.205075] mlx5_ib: disagrees about version of symbol ib_uverbs_flow_resources_free
[ 5064.205076] mlx5_ib: Unknown symbol ib_uverbs_flow_resources_free (err -22)
[ 5064.205086] mlx5_ib: disagrees about version of symbol ib_umem_odp_map_dma_and_lock
[ 5064.205087] mlx5_ib: Unknown symbol ib_umem_odp_map_dma_and_lock (err -22)
[ 5064.205096] mlx5_ib: disagrees about version of symbol ib_free_cq
[ 5064.205097] mlx5_ib: Unknown symbol ib_free_cq (err -22)
[ 5064.205103] mlx5_ib: disagrees about version of symbol mlx5_eq_notifier_unregister
[ 5064.205105] mlx5_ib: Unknown symbol mlx5_eq_notifier_unregister (err -22)
[ 5064.205110] mlx5_ib: disagrees about version of symbol mlx5_query_port_vl_hw_cap
[ 5064.205111] mlx5_ib: Unknown symbol mlx5_query_port_vl_hw_cap (err -22)
[ 5064.205116] mlx5_ib: disagrees about version of symbol mlx5_query_hca_vport_pkey
[ 5064.205117] mlx5_ib: Unknown symbol mlx5_query_hca_vport_pkey (err -22)
[ 5064.205130] mlx5_ib: disagrees about version of symbol mlx5_frag_buf_alloc_node
[ 5064.205132] mlx5_ib: Unknown symbol mlx5_frag_buf_alloc_node (err -22)
[ 5064.205147] mlx5_ib: disagrees about version of symbol _uverbs_alloc
[ 5064.205148] mlx5_ib: Unknown symbol _uverbs_alloc (err -22)
[ 5064.205153] mlx5_ib: disagrees about version of symbol mlx5_fc_destroy
[ 5064.205154] mlx5_ib: Unknown symbol mlx5_fc_destroy (err -22)
[ 5064.205162] mlx5_ib: disagrees about version of symbol mlx5_lag_is_master
[ 5064.205164] mlx5_ib: Unknown symbol mlx5_lag_is_master (err -22)
[ 5064.205170] mlx5_ib: disagrees about version of symbol mlx5_nic_vport_unaffiliate_multiport
[ 5064.205172] mlx5_ib: Unknown symbol mlx5_nic_vport_unaffiliate_multiport (err -22)
[ 5064.205182] mlx5_ib: disagrees about version of symbol mlx5_query_hca_vport_context
[ 5064.205183] mlx5_ib: Unknown symbol mlx5_query_hca_vport_context (err -22)
[ 5064.205188] mlx5_ib: disagrees about version of symbol ib_query_pkey
[ 5064.205190] mlx5_ib: Unknown symbol ib_query_pkey (err -22)
[ 5064.205197] mlx5_ib: disagrees about version of symbol uverbs_uobject_put
[ 5064.205198] mlx5_ib: Unknown symbol uverbs_uobject_put (err -22)
[ 5064.205202] mlx5_ib: disagrees about version of symbol mlx5_core_roce_gid_set
[ 5064.205204] mlx5_ib: Unknown symbol mlx5_core_roce_gid_set (err -22)
[ 5064.205213] mlx5_ib: disagrees about version of symbol mlx5_query_port_oper_mtu
[ 5064.205214] mlx5_ib: Unknown symbol mlx5_query_port_oper_mtu (err -22)
[ 5064.205219] mlx5_ib: disagrees about version of symbol mlx5_nic_vport_enable_roce
[ 5064.205220] mlx5_ib: Unknown symbol mlx5_nic_vport_enable_roce (err -22)
[ 5064.205225] mlx5_ib: disagrees about version of symbol ib_port_immutable_read
[ 5064.205227] mlx5_ib: Unknown symbol ib_port_immutable_read (err -22)
[ 5064.205232] mlx5_ib: disagrees about version of symbol ib_create_qp_kernel
[ 5064.205233] mlx5_ib: Unknown symbol ib_create_qp_kernel (err -22)
[ 5064.205240] mlx5_ib: disagrees about version of symbol uverbs_copy_to
[ 5064.205241] mlx5_ib: Unknown symbol uverbs_copy_to (err -22)
[ 5064.205250] mlx5_ib: disagrees about version of symbol flow_resources_add
[ 5064.205252] mlx5_ib: Unknown symbol flow_resources_add (err -22)
[ 5064.205256] mlx5_ib: disagrees about version of symbol mlx5_core_modify_rq
[ 5064.205257] mlx5_ib: Unknown symbol mlx5_core_modify_rq (err -22)
[ 5064.205261] mlx5_ib: disagrees about version of symbol mlx5_core_query_mkey
[ 5064.205263] mlx5_ib: Unknown symbol mlx5_core_query_mkey (err -22)
[ 5064.205275] mlx5_ib: disagrees about version of symbol uverbs_destroy_def_handler
[ 5064.205276] mlx5_ib: Unknown symbol uverbs_destroy_def_handler (err -22)
[ 5064.205280] mlx5_ib: disagrees about version of symbol mlx5_qp_debugfs_init
[ 5064.205282] mlx5_ib: Unknown symbol mlx5_qp_debugfs_init (err -22)
[ 5064.205287] mlx5_ib: disagrees about version of symbol ib_dealloc_pd_user
[ 5064.205288] mlx5_ib: Unknown symbol ib_dealloc_pd_user (err -22)
[ 5064.205292] mlx5_ib: disagrees about version of symbol mlx5_core_modify_tis
[ 5064.205293] mlx5_ib: Unknown symbol mlx5_core_modify_tis (err -22)
[ 5064.205298] mlx5_ib: disagrees about version of symbol rdma_port_get_link_layer
[ 5064.205300] mlx5_ib: Unknown symbol rdma_port_get_link_layer (err -22)
[ 5064.205304] mlx5_ib: disagrees about version of symbol uverbs_get_flags64
[ 5064.205306] mlx5_ib: Unknown symbol uverbs_get_flags64 (err -22)
[ 5064.205315] mlx5_ib: disagrees about version of symbol mlx5_eswitch_get_total_vports
[ 5064.205316] mlx5_ib: Unknown symbol mlx5_eswitch_get_total_vports (err -22)
[ 5064.205320] mlx5_ib: disagrees about version of symbol mlx5_core_destroy_cq
[ 5064.205322] mlx5_ib: Unknown symbol mlx5_core_destroy_cq (err -22)
[ 5064.205326] mlx5_ib: disagrees about version of symbol mlx5_core_reserved_gids_count
[ 5064.205327] mlx5_ib: Unknown symbol mlx5_core_reserved_gids_count (err -22)
[ 5064.205342] mlx5_ib: Unknown symbol mlx5_lag_get_peer_mdev (err -2)
[ 5064.205348] mlx5_ib: disagrees about version of symbol mlx5_debugfs_root
[ 5064.205350] mlx5_ib: Unknown symbol mlx5_debugfs_root (err -22)
[ 5064.205355] mlx5_ib: disagrees about version of symbol mlx5_core_modify_cq_moderation
[ 5064.205356] mlx5_ib: Unknown symbol mlx5_core_modify_cq_moderation (err -22)
[ 5064.205361] mlx5_ib: disagrees about version of symbol ib_umem_copy_from
[ 5064.205362] mlx5_ib: Unknown symbol ib_umem_copy_from (err -22)
[ 5064.205378] mlx5_ib: Unknown symbol mlx5_accel_esp_destroy_xfrm (err -2)
[ 5064.205381] mlx5_ib: disagrees about version of symbol mlx5_qp_debugfs_cleanup
[ 5064.205383] mlx5_ib: Unknown symbol mlx5_qp_debugfs_cleanup (err -22)
[ 5064.205386] mlx5_ib: disagrees about version of symbol mlx5_eq_disable
[ 5064.205388] mlx5_ib: Unknown symbol mlx5_eq_disable (err -22)
[ 5064.205391] mlx5_ib: disagrees about version of symbol mlx5_cmd_cleanup_async_ctx
[ 5064.205393] mlx5_ib: Unknown symbol mlx5_cmd_cleanup_async_ctx (err -22)
[ 5064.205409] mlx5_ib: Unknown symbol mlx5_cmd_free_uar (err -2)
[ 5064.205423] mlx5_ib: Unknown symbol mlx5_cmd_alloc_uar (err -2)
[ 5064.205427] mlx5_ib: disagrees about version of symbol mlx5_rl_remove_rate_raw
[ 5064.205429] mlx5_ib: Unknown symbol mlx5_rl_remove_rate_raw (err -22)
[ 5064.205433] mlx5_ib: disagrees about version of symbol rdma_roce_rescan_device
[ 5064.205435] mlx5_ib: Unknown symbol rdma_roce_rescan_device (err -22)
[ 5064.205449] mlx5_ib: Unknown symbol mlx5_core_query_ib_ppcnt (err -2)
[ 5064.205453] mlx5_ib: disagrees about version of symbol mlx5_alloc_bfreg
[ 5064.205454] mlx5_ib: Unknown symbol mlx5_alloc_bfreg (err -22)
[ 5064.205457] mlx5_ib: disagrees about version of symbol mlx5_eq_destroy_generic
[ 5064.205459] mlx5_ib: Unknown symbol mlx5_eq_destroy_generic (err -22)
[ 5064.205473] mlx5_ib: Unknown symbol mlx5_vector2eqn (err -2)
[ 5064.205480] mlx5_ib: disagrees about version of symbol mlx5_lag_is_active
[ 5064.205482] mlx5_ib: Unknown symbol mlx5_lag_is_active (err -22)
[ 5064.205485] mlx5_ib: disagrees about version of symbol mlx5_free_bfreg
[ 5064.205486] mlx5_ib: Unknown symbol mlx5_free_bfreg (err -22)
[ 5064.205491] mlx5_ib: disagrees about version of symbol mlx5_cmd_destroy_vport_lag
[ 5064.205492] mlx5_ib: Unknown symbol mlx5_cmd_destroy_vport_lag (err -22)
[ 5064.205497] mlx5_ib: disagrees about version of symbol ib_set_device_ops
[ 5064.205498] mlx5_ib: Unknown symbol ib_set_device_ops (err -22)
[ 5064.205503] mlx5_ib: disagrees about version of symbol rdma_user_mmap_entry_put
[ 5064.205504] mlx5_ib: Unknown symbol rdma_user_mmap_entry_put (err -22)
[ 5064.205509] mlx5_ib: disagrees about version of symbol mlx5_core_access_reg
[ 5064.205510] mlx5_ib: Unknown symbol mlx5_core_access_reg (err -22)
