# lsmod | grep mlx
mlx5_ib               446464  12
mlx5_core            2203648  1 mlx5_ib
mlxfw                  32768  1 mlx5_core
mlxdevm               176128  1 mlx5_core
ib_uverbs             163840  50 rdma_ucm,mlx5_ib
ib_core               417792  8 rdma_cm,ib_ipoib,iw_cm,ib_umad,rdma_ucm,ib_uverbs,mlx5_ib,ib_cm
mlx_compat             69632  12 rdma_cm,ib_ipoib,mlxdevm,mlxfw,iw_cm,ib_umad,ib_core,rdma_ucm,ib_uverbs,mlx5_ib,ib_cm,mlx5_core
psample                20480  1 mlx5_core
tls                   114688  1 mlx5_core

# modinfo mlx5_ib
filename:       /lib/modules/5.15.0-1087-azure/kernel/drivers/infiniband/hw/mlx5/mlx5_ib.ko
license:        Dual BSD/GPL
description:    Mellanox 5th generation network adapters (ConnectX series) IB driver
author:         Eli Cohen <eli@mellanox.com>
srcversion:     ACF3DC84F2E17FED5AC00D7
alias:          auxiliary:mlx5_core.rdma
alias:          auxiliary:mlx5_core.multiport
alias:          auxiliary:mlx5_core.rdma-rep
depends:        mlx5_core,ib_core,ib_uverbs
retpoline:      Y
intree:         Y
name:           mlx5_ib
vermagic:       5.15.0-1087-azure SMP mod_unload modversions
sig_id:         PKCS#7
signer:         Build time autogenerated kernel key
sig_key:        37:D1:D0:7E:E6:01:12:9D:44:3B:F6:3A:03:58:05:63:92:E9:48:10
sig_hashalgo:   sha512
signature:      77:8B:08:E2:2F:F4:16:05:A8:97:0D:E0:BE:07:1A:FB:1C:C3:AA:D0:
		FF:EA:8C:5C:16:AE:33:04:EE:2A:D3:F7:B2:63:8B:0B:B4:74:DE:AF:
		77:2A:EF:93:65:A2:16:63:AC:4E:DD:FD:57:39:A8:91:65:47:09:8D:
		84:7F:5F:06:2D:2D:64:DA:F4:2C:77:E3:AF:04:E4:8F:C7:D8:4D:A6:
		89:0B:21:D0:24:CF:64:AF:42:BF:1E:A5:43:AC:47:DB:6D:7D:BF:77:
		D9:E7:B4:35:A9:3B:CB:79:31:B3:EC:7F:5F:4D:F1:9E:0E:E4:D8:18:
		24:4C:F8:F5:5A:3B:5F:F8:99:21:62:F4:51:F6:30:EC:4B:7C:37:D2:
		88:C3:2A:4A:97:63:EA:AE:35:61:C2:5E:02:EF:C3:79:50:BD:66:CA:
		46:AA:E5:FB:2D:F9:57:06:15:F1:09:A2:C1:63:4A:9B:CC:C2:D1:0B:
		33:2F:6C:88:B2:67:5F:AA:A7:0D:A4:FB:C1:1E:82:78:1D:8B:A5:34:
		8A:C0:32:FE:95:43:6F:56:A1:64:A6:27:27:D1:25:2C:D4:61:EE:91:
		4C:57:E7:D2:89:A8:97:EB:CB:86:37:1F:93:99:79:92:4E:40:46:47:
		40:22:2C:B6:EA:DC:6C:D7:C4:07:24:86:A8:4F:E5:F3:73:52:76:C0:
		4E:96:C4:F7:8F:76:47:66:CD:35:05:FE:C2:7C:26:61:69:17:8F:E5:
		C2:77:BB:41:A5:7A:30:77:A5:6B:B4:DD:92:F6:89:37:ED:0F:0E:5C:
		AD:C8:F1:58:B5:18:5A:33:CA:A4:AB:BD:4D:EB:97:B2:7B:B4:F2:3A:
		74:10:B9:A2:67:98:D3:09:51:8A:87:E9:4E:5F:AE:71:7D:7D:C8:E7:
		22:27:EF:55:C0:45:2C:F1:34:AE:FF:61:D3:06:5E:70:65:29:72:75:
		5C:15:4A:05:89:FB:41:64:D2:D4:27:25:41:20:11:F8:87:71:E2:A4:
		20:8B:C2:0B:51:92:01:D7:FE:E5:0F:FB:D1:0F:12:0C:72:4C:63:4D:
		ED:11:34:7E:FB:34:D0:3F:87:62:B4:48:62:F8:10:30:E1:22:AC:B1:
		B8:3E:89:59:83:F5:2F:99:00:29:F8:87:A8:46:D2:85:9E:8A:5A:0D:
		A8:AC:FE:34:F4:46:26:53:8C:6F:0D:FB:A9:2E:CA:30:D8:78:3F:D5:
		96:73:FD:25:45:AE:1D:71:B2:E4:A4:60:B2:08:43:DF:E2:36:FD:5C:
		54:19:31:AC:FD:A9:38:F3:FE:6D:21:9E:24:84:B7:12:23:84:F1:D1:
		2E:4B:1B:8B:9A:14:0A:82:41:EA:10:7D


# modinfo mlx5_core
filename:       /lib/modules/5.15.0-1087-azure/kernel/drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.ko
license:        Dual BSD/GPL
description:    Mellanox 5th generation network adapters (ConnectX series) core driver
author:         Eli Cohen <eli@mellanox.com>
srcversion:     5C665939D32BB564858EA35
alias:          auxiliary:mlx5_core.eth
alias:          pci:v000015B3d0000A2DFsv*sd*bc*sc*i*
alias:          pci:v000015B3d0000A2DCsv*sd*bc*sc*i*
alias:          pci:v000015B3d0000A2D6sv*sd*bc*sc*i*
alias:          pci:v000015B3d0000A2D3sv*sd*bc*sc*i*
alias:          pci:v000015B3d0000A2D2sv*sd*bc*sc*i*
alias:          pci:v000015B3d00001023sv*sd*bc*sc*i*
alias:          pci:v000015B3d00001021sv*sd*bc*sc*i*
alias:          pci:v000015B3d0000101Fsv*sd*bc*sc*i*
alias:          pci:v000015B3d0000101Esv*sd*bc*sc*i*
alias:          pci:v000015B3d0000101Dsv*sd*bc*sc*i*
alias:          pci:v000015B3d0000101Csv*sd*bc*sc*i*
alias:          pci:v000015B3d0000101Bsv*sd*bc*sc*i*
alias:          pci:v000015B3d0000101Asv*sd*bc*sc*i*
alias:          pci:v000015B3d00001019sv*sd*bc*sc*i*
alias:          pci:v000015B3d00001018sv*sd*bc*sc*i*
alias:          pci:v000015B3d00001017sv*sd*bc*sc*i*
alias:          pci:v000015B3d00001016sv*sd*bc*sc*i*
alias:          pci:v000015B3d00001015sv*sd*bc*sc*i*
alias:          pci:v000015B3d00001014sv*sd*bc*sc*i*
alias:          pci:v000015B3d00001013sv*sd*bc*sc*i*
alias:          pci:v000015B3d00001012sv*sd*bc*sc*i*
alias:          pci:v000015B3d00001011sv*sd*bc*sc*i*
alias:          auxiliary:mlx5_core.eth-rep
alias:          auxiliary:mlx5_core.sf
depends:        tls,mlxfw,psample
retpoline:      Y
intree:         Y
name:           mlx5_core
vermagic:       5.15.0-1087-azure SMP mod_unload modversions
sig_id:         PKCS#7
signer:         Build time autogenerated kernel key
sig_key:        37:D1:D0:7E:E6:01:12:9D:44:3B:F6:3A:03:58:05:63:92:E9:48:10
sig_hashalgo:   sha512
signature:      62:D6:95:A9:42:08:7B:07:F8:1A:A2:50:6F:5A:0A:DB:A5:AB:4D:29:
		93:E9:11:B6:11:17:C5:A9:A4:59:A0:1B:54:14:50:B6:3D:DE:41:DE:
		76:B9:1F:B8:2F:31:AD:F0:A8:E0:CF:D0:9B:DF:03:9C:BA:94:26:F8:
		CE:55:12:7D:E5:47:64:3C:99:F6:18:A4:EA:E9:D3:BE:39:62:1C:C0:
		C8:39:88:91:E1:5C:CB:67:9F:72:7A:32:5B:28:0E:24:E2:FF:59:B4:
		D4:91:DB:A8:0F:3F:3D:68:44:13:FA:A9:CD:00:40:B4:3D:17:B1:B9:
		20:C2:C5:CD:64:9A:D3:A8:B2:79:58:E3:8B:4A:C6:A7:7F:EF:36:EF:
		97:65:EC:57:1E:76:69:9B:8C:41:8A:AB:B7:89:A0:62:C6:DD:53:16:
		21:77:E5:DB:28:3B:2A:3E:3B:53:CD:C4:86:55:1F:EA:10:20:0D:B0:
		F7:BE:4C:87:9B:02:C3:93:67:AA:BC:0D:E1:8D:12:8F:46:5C:EC:0C:
		1F:5E:55:03:8F:27:C9:E5:1A:79:43:BF:BA:26:3E:21:0C:48:02:5F:
		95:02:8B:DF:5B:BD:09:91:52:FF:C2:45:AE:18:83:88:51:A9:74:3B:
		07:FE:AF:2D:17:2E:99:CB:09:60:62:69:B4:01:13:A6:C5:7E:35:75:
		F5:1A:42:96:3E:9C:CB:A3:9A:42:2F:E2:FC:5C:DD:00:1C:9E:11:79:
		2B:C3:6A:45:D6:C4:FA:32:52:2B:4C:2F:CA:9E:EC:77:50:AA:83:A3:
		71:57:B5:B9:24:13:2A:28:69:AC:1E:57:FD:76:8F:A0:54:38:93:59:
		15:8D:C4:E4:3C:01:6B:B1:34:92:AE:3D:1B:64:38:75:7E:B2:F5:88:
		9D:AB:7B:64:09:11:2D:E6:8D:C8:47:D3:96:86:30:74:C7:3C:31:46:
		8F:77:F8:B2:DD:CC:8F:69:F2:0E:21:A1:A3:90:94:99:4E:3A:AF:6C:
		52:30:9E:B2:0F:F4:0B:97:49:94:8C:1E:16:10:7F:6B:7E:8F:59:E9:
		D3:35:FD:AD:DF:EF:AC:E5:4B:FF:10:88:61:A2:F2:FB:EA:7B:8B:B8:
		FB:07:8E:41:E4:06:DA:73:45:2C:45:FB:40:6C:2C:95:42:9A:DB:DB:
		0C:40:4B:27:0E:3B:89:07:16:EC:9C:30:C2:57:5E:85:4F:87:78:F5:
		E5:E9:CF:48:96:5F:C7:49:7C:F0:66:D8:07:C2:8F:03:DE:D3:C0:E4:
		4E:D9:B1:74:30:F0:DF:0D:C1:52:38:72:4A:B0:6C:AF:BB:BB:91:25:
		42:58:9B:AC:7E:56:18:41:AE:67:92:19
parm:           debug_mask:debug mask: 1 = dump cmd data, 2 = dump cmd exec time, 3 = both. Default=0 (uint)
parm:           prof_sel:profile selector. Valid range 0 - 2 (uint)

# dmesg
[    0.000000] Linux version 5.15.0-1087-azure (buildd@lcy02-amd64-011) (gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #96-Ubuntu SMP Fri Mar 28 20:31:27 UTC 2025 (Ubuntu 5.15.0-1087.96-azure 5.15.178)
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-5.15.0-1087-azure root=PARTUUID=576855f9-6ec4-43c3-a073-17116ff21b7b ro console=tty1 console=ttyS0 earlyprintk=ttyS0 nvme_core.io_timeout=240 panic=-1
[    0.000000] KERNEL supported cpus:
[    0.000000]   Intel GenuineIntel
[    0.000000]   AMD AuthenticAMD
[    0.000000]   Hygon HygonGenuine
[    0.000000]   Centaur CentaurHauls
[    0.000000]   zhaoxin   Shanghai
[    0.000000] BIOS-provided physical RAM map:
[    0.000000] BIOS-e820: [mem 0x0000000000000000-0x000000000009ffff] usable
[    0.000000] BIOS-e820: [mem 0x00000000000c0000-0x00000000000fffff] reserved
[    0.000000] BIOS-e820: [mem 0x0000000000100000-0x000000003ff40fff] usable
[    0.000000] BIOS-e820: [mem 0x000000003ff41000-0x000000003ffc8fff] reserved
[    0.000000] BIOS-e820: [mem 0x000000003ffc9000-0x000000003fffafff] ACPI data
[    0.000000] BIOS-e820: [mem 0x000000003fffb000-0x000000003fffefff] ACPI NVS
[    0.000000] BIOS-e820: [mem 0x000000003ffff000-0x000000003fffffff] usable
[    0.000000] BIOS-e820: [mem 0x0000000100000000-0x000000e1bfffffff] usable
[    0.000000] printk: bootconsole [earlyser0] enabled
[    0.000000] NX (Execute Disable) protection: active
[    0.000000] efi: EFI v2.70 by Microsoft
[    0.000000] efi: ACPI=0x3fffa000 ACPI 2.0=0x3fffa014 SMBIOS=0x3ff85000 SMBIOS 3.0=0x3ff83000 MEMATTR=0x3ee87018 MOKvar=0x3ff80000 RNG=0x3ffd0018
[    0.000000] random: crng init done
[    0.000000] secureboot: Secure boot disabled
[    0.000000] SMBIOS 3.1.0 present.
[    0.000000] DMI: Microsoft Corporation Virtual Machine/Virtual Machine, BIOS Hyper-V UEFI Release v4.1 03/08/2024
[    0.000000] Hypervisor detected: Microsoft Hyper-V
[    0.000000] Hyper-V: privilege flags low 0xae7f, high 0x3b8030, hints 0x40c2c, misc 0x40bed7b6
[    0.000000] Hyper-V Host Build:20348-10.0-3-0.3077
[    0.000000] Hyper-V: Nested features: 0x0
[    0.000000] Hyper-V: LAPIC Timer Frequency: 0xc3500
[    0.000000] Hyper-V: Using hypercall for remote TLB flush
[    0.000000] clocksource: hyperv_clocksource_tsc_page: mask: 0xffffffffffffffff max_cycles: 0x24e6a1710, max_idle_ns: 440795202120 ns
[    0.000003] tsc: Detected 2445.449 MHz processor
[    0.002408] e820: update [mem 0x00000000-0x00000fff] usable ==> reserved
[    0.002411] e820: remove [mem 0x000a0000-0x000fffff] usable
[    0.002417] last_pfn = 0xe1c0000 max_arch_pfn = 0x400000000
[    0.005426] x86/PAT: Configuration [0-7]: WB  WC  UC- UC  WB  WP  UC- WT
[    0.009022] e820: update [mem 0x40000000-0xffffffff] usable ==> reserved
[    0.010707] last_pfn = 0x40000 max_arch_pfn = 0x400000000
[    0.018340] Using GB pages for direct mapping
[    0.020828] secureboot: Secure boot disabled
[    0.023052] ACPI: Early table checksum verification disabled
[    0.025953] ACPI: RSDP 0x000000003FFFA014 000024 (v02 VRTUAL)
[    0.028902] ACPI: XSDT 0x000000003FFF90E8 00006C (v01 VRTUAL MICROSFT 00000001 MSFT 00000001)
[    0.033286] ACPI: FACP 0x000000003FFF8000 000114 (v06 VRTUAL MICROSFT 00000001 MSFT 00000001)
[    0.037635] ACPI: DSDT 0x000000003FFD6000 01E184 (v02 MSFTVM DSDT01   00000001 MSFT 05000000)
[    0.041892] ACPI: FACS 0x000000003FFFE000 000040
[    0.044233] ACPI: OEM0 0x000000003FFF7000 000064 (v01 VRTUAL MICROSFT 00000001 MSFT 00000001)
[    0.048628] ACPI: SPCR 0x000000003FFF6000 000050 (v02 VRTUAL MICROSFT 00000001 MSFT 00000001)
[    0.053009] ACPI: WAET 0x000000003FFF5000 000028 (v01 VRTUAL MICROSFT 00000001 MSFT 00000001)
[    0.057374] ACPI: APIC 0x000000003FFD5000 000348 (v04 VRTUAL MICROSFT 00000001 MSFT 00000001)
[    0.061790] ACPI: SRAT 0x000000003FFD4000 000E78 (v02 VRTUAL MICROSFT 00000001 MSFT 00000001)
[    0.066228] ACPI: SLIT 0x000000003FFD3000 00003C (v01 VRTUAL MICROSFT 00000001 MSFT 00000001)
[    0.070585] ACPI: BGRT 0x000000003FFD2000 000038 (v01 VRTUAL MICROSFT 00000001 MSFT 00000001)
[    0.074921] ACPI: FPDT 0x000000003FFD1000 000034 (v01 VRTUAL MICROSFT 00000001 MSFT 00000001)
[    0.079256] ACPI: Reserving FACP table memory at [mem 0x3fff8000-0x3fff8113]
[    0.082942] ACPI: Reserving DSDT table memory at [mem 0x3ffd6000-0x3fff4183]
[    0.086679] ACPI: Reserving FACS table memory at [mem 0x3fffe000-0x3fffe03f]
[    0.090182] ACPI: Reserving OEM0 table memory at [mem 0x3fff7000-0x3fff7063]
[    0.093767] ACPI: Reserving SPCR table memory at [mem 0x3fff6000-0x3fff604f]
[    0.097359] ACPI: Reserving WAET table memory at [mem 0x3fff5000-0x3fff5027]
[    0.100986] ACPI: Reserving APIC table memory at [mem 0x3ffd5000-0x3ffd5347]
[    0.104617] ACPI: Reserving SRAT table memory at [mem 0x3ffd4000-0x3ffd4e77]
[    0.108244] ACPI: Reserving SLIT table memory at [mem 0x3ffd3000-0x3ffd303b]
[    0.111904] ACPI: Reserving BGRT table memory at [mem 0x3ffd2000-0x3ffd2037]
[    0.115508] ACPI: Reserving FPDT table memory at [mem 0x3ffd1000-0x3ffd1033]
[    0.119180] SRAT: PXM 0 -> APIC 0x00 -> Node 0
[    0.121439] SRAT: PXM 0 -> APIC 0x01 -> Node 0
[    0.123745] SRAT: PXM 0 -> APIC 0x02 -> Node 0
[    0.126006] SRAT: PXM 0 -> APIC 0x03 -> Node 0
[    0.128241] SRAT: PXM 0 -> APIC 0x04 -> Node 0
[    0.130469] SRAT: PXM 0 -> APIC 0x05 -> Node 0
[    0.132726] SRAT: PXM 0 -> APIC 0x06 -> Node 0
[    0.134952] SRAT: PXM 0 -> APIC 0x07 -> Node 0
[    0.137152] SRAT: PXM 0 -> APIC 0x08 -> Node 0
[    0.139354] SRAT: PXM 0 -> APIC 0x09 -> Node 0
[    0.141590] SRAT: PXM 0 -> APIC 0x0a -> Node 0
[    0.143891] SRAT: PXM 0 -> APIC 0x0b -> Node 0
[    0.146176] SRAT: PXM 0 -> APIC 0x0c -> Node 0
[    0.148466] SRAT: PXM 0 -> APIC 0x0d -> Node 0
[    0.150750] SRAT: PXM 0 -> APIC 0x0e -> Node 0
[    0.153027] SRAT: PXM 0 -> APIC 0x0f -> Node 0
[    0.155336] SRAT: PXM 0 -> APIC 0x10 -> Node 0
[    0.157618] SRAT: PXM 0 -> APIC 0x11 -> Node 0
[    0.159912] SRAT: PXM 0 -> APIC 0x12 -> Node 0
[    0.162140] SRAT: PXM 0 -> APIC 0x13 -> Node 0
[    0.164472] SRAT: PXM 0 -> APIC 0x14 -> Node 0
[    0.166712] SRAT: PXM 0 -> APIC 0x15 -> Node 0
[    0.168997] SRAT: PXM 0 -> APIC 0x16 -> Node 0
[    0.171269] SRAT: PXM 0 -> APIC 0x17 -> Node 0
[    0.173519] SRAT: PXM 1 -> APIC 0x18 -> Node 1
[    0.175772] SRAT: PXM 1 -> APIC 0x19 -> Node 1
[    0.177983] SRAT: PXM 1 -> APIC 0x1a -> Node 1
[    0.180226] SRAT: PXM 1 -> APIC 0x1b -> Node 1
[    0.182431] SRAT: PXM 1 -> APIC 0x1c -> Node 1
[    0.184661] SRAT: PXM 1 -> APIC 0x1d -> Node 1
[    0.186881] SRAT: PXM 1 -> APIC 0x1e -> Node 1
[    0.189138] SRAT: PXM 1 -> APIC 0x1f -> Node 1
[    0.191452] SRAT: PXM 1 -> APIC 0x20 -> Node 1
[    0.193739] SRAT: PXM 1 -> APIC 0x21 -> Node 1
[    0.196139] SRAT: PXM 1 -> APIC 0x22 -> Node 1
[    0.198434] SRAT: PXM 1 -> APIC 0x23 -> Node 1
[    0.200751] SRAT: PXM 1 -> APIC 0x24 -> Node 1
[    0.203094] SRAT: PXM 1 -> APIC 0x25 -> Node 1
[    0.205560] SRAT: PXM 1 -> APIC 0x26 -> Node 1
[    0.207903] SRAT: PXM 1 -> APIC 0x27 -> Node 1
[    0.210184] SRAT: PXM 1 -> APIC 0x28 -> Node 1
[    0.212464] SRAT: PXM 1 -> APIC 0x29 -> Node 1
[    0.214773] SRAT: PXM 1 -> APIC 0x2a -> Node 1
[    0.217039] SRAT: PXM 1 -> APIC 0x2b -> Node 1
[    0.219288] SRAT: PXM 1 -> APIC 0x2c -> Node 1
[    0.221546] SRAT: PXM 1 -> APIC 0x2d -> Node 1
[    0.223789] SRAT: PXM 1 -> APIC 0x2e -> Node 1
[    0.226078] SRAT: PXM 1 -> APIC 0x2f -> Node 1
[    0.228534] SRAT: PXM 2 -> APIC 0x40 -> Node 2
[    0.230751] SRAT: PXM 2 -> APIC 0x41 -> Node 2
[    0.233018] SRAT: PXM 2 -> APIC 0x42 -> Node 2
[    0.235285] SRAT: PXM 2 -> APIC 0x43 -> Node 2
[    0.237522] SRAT: PXM 2 -> APIC 0x44 -> Node 2
[    0.239765] SRAT: PXM 2 -> APIC 0x45 -> Node 2
[    0.242033] SRAT: PXM 2 -> APIC 0x46 -> Node 2
[    0.244324] SRAT: PXM 2 -> APIC 0x47 -> Node 2
[    0.246642] SRAT: PXM 2 -> APIC 0x48 -> Node 2
[    0.248952] SRAT: PXM 2 -> APIC 0x49 -> Node 2
[    0.251277] SRAT: PXM 2 -> APIC 0x4a -> Node 2
[    0.253624] SRAT: PXM 2 -> APIC 0x4b -> Node 2
[    0.256059] SRAT: PXM 2 -> APIC 0x4c -> Node 2
[    0.258366] SRAT: PXM 2 -> APIC 0x4d -> Node 2
[    0.260704] SRAT: PXM 2 -> APIC 0x4e -> Node 2
[    0.263062] SRAT: PXM 2 -> APIC 0x4f -> Node 2
[    0.265376] SRAT: PXM 2 -> APIC 0x50 -> Node 2
[    0.267674] SRAT: PXM 2 -> APIC 0x51 -> Node 2
[    0.269954] SRAT: PXM 2 -> APIC 0x52 -> Node 2
[    0.272233] SRAT: PXM 2 -> APIC 0x53 -> Node 2
[    0.274495] SRAT: PXM 2 -> APIC 0x54 -> Node 2
[    0.276786] SRAT: PXM 2 -> APIC 0x55 -> Node 2
[    0.279036] SRAT: PXM 2 -> APIC 0x56 -> Node 2
[    0.281263] SRAT: PXM 2 -> APIC 0x57 -> Node 2
[    0.283483] SRAT: PXM 3 -> APIC 0x58 -> Node 3
[    0.285742] SRAT: PXM 3 -> APIC 0x59 -> Node 3
[    0.287962] SRAT: PXM 3 -> APIC 0x5a -> Node 3
[    0.290246] SRAT: PXM 3 -> APIC 0x5b -> Node 3
[    0.292563] SRAT: PXM 3 -> APIC 0x5c -> Node 3
[    0.294870] SRAT: PXM 3 -> APIC 0x5d -> Node 3
[    0.297157] SRAT: PXM 3 -> APIC 0x5e -> Node 3
[    0.299441] SRAT: PXM 3 -> APIC 0x5f -> Node 3
[    0.301786] SRAT: PXM 3 -> APIC 0x60 -> Node 3
[    0.304083] SRAT: PXM 3 -> APIC 0x61 -> Node 3
[    0.306477] SRAT: PXM 3 -> APIC 0x62 -> Node 3
[    0.308810] SRAT: PXM 3 -> APIC 0x63 -> Node 3
[    0.311082] SRAT: PXM 3 -> APIC 0x64 -> Node 3
[    0.313345] SRAT: PXM 3 -> APIC 0x65 -> Node 3
[    0.315613] SRAT: PXM 3 -> APIC 0x66 -> Node 3
[    0.317917] SRAT: PXM 3 -> APIC 0x67 -> Node 3
[    0.320151] SRAT: PXM 3 -> APIC 0x68 -> Node 3
[    0.322419] SRAT: PXM 3 -> APIC 0x69 -> Node 3
[    0.324718] SRAT: PXM 3 -> APIC 0x6a -> Node 3
[    0.326978] SRAT: PXM 3 -> APIC 0x6b -> Node 3
[    0.329215] SRAT: PXM 3 -> APIC 0x6c -> Node 3
[    0.331424] SRAT: PXM 3 -> APIC 0x6d -> Node 3
[    0.333631] SRAT: PXM 3 -> APIC 0x6e -> Node 3
[    0.335907] SRAT: PXM 3 -> APIC 0x6f -> Node 3
[    0.338219] ACPI: SRAT: Node 0 PXM 0 [mem 0x00000000-0x3fffffff] hotplug
[    0.341731] ACPI: SRAT: Node 0 PXM 0 [mem 0x100000000-0x38ffffffff] hotplug
[    0.345317] ACPI: SRAT: Node 1 PXM 1 [mem 0x3900000000-0x713fffffff] hotplug
[    0.349118] ACPI: SRAT: Node 2 PXM 2 [mem 0x7140000000-0xa97fffffff] hotplug
[    0.352878] ACPI: SRAT: Node 3 PXM 3 [mem 0xa980000000-0xe1bfffffff] hotplug
[    0.356588] ACPI: SRAT: Node 0 PXM 0 [mem 0xe1c0000000-0xe88fffffff] hotplug
[    0.360235] ACPI: SRAT: Node 0 PXM 0 [mem 0x22000000000-0x297ffffffff] hotplug
[    0.363935] ACPI: SRAT: Node 0 PXM 0 [mem 0x40000000000-0x4ffffffffff] hotplug
[    0.367705] ACPI: SRAT: Node 0 PXM 0 [mem 0x80000000000-0x9ffffffffff] hotplug
[    0.371437] ACPI: SRAT: Node 0 PXM 0 [mem 0x100000000000-0x13ffffffffff] hotplug
[    0.375265] ACPI: SRAT: Node 0 PXM 0 [mem 0x200000000000-0x27ffffffffff] hotplug
[    0.379081] ACPI: SRAT: Node 0 PXM 0 [mem 0x400000000000-0x4fffffffffff] hotplug
[    0.382865] ACPI: SRAT: Node 0 PXM 0 [mem 0x800000000000-0x9fffffffffff] hotplug
[    0.386660] ACPI: SRAT: Node 0 PXM 0 [mem 0x1000000000000-0x13fffffffffff] hotplug
[    0.390556] ACPI: SRAT: Node 0 PXM 0 [mem 0x2000000000000-0x27fffffffffff] hotplug
[    0.394446] ACPI: SRAT: Node 0 PXM 0 [mem 0x4000000000000-0x4ffffffffffff] hotplug
[    0.398334] ACPI: SRAT: Node 0 PXM 0 [mem 0x8000000000000-0x9ffffffffffff] hotplug
[    0.402229] ACPI: SRAT: Node 1 PXM 1 [mem 0xe890000000-0xef5fffffff] hotplug
[    0.405878] ACPI: SRAT: Node 1 PXM 1 [mem 0x29800000000-0x30fffffffff] hotplug
[    0.409579] ACPI: SRAT: Node 1 PXM 1 [mem 0x50000000000-0x5ffffffffff] hotplug
[    0.413287] ACPI: SRAT: Node 1 PXM 1 [mem 0xa0000000000-0xbffffffffff] hotplug
[    0.417017] ACPI: SRAT: Node 1 PXM 1 [mem 0x140000000000-0x17ffffffffff] hotplug
[    0.420821] ACPI: SRAT: Node 1 PXM 1 [mem 0x280000000000-0x2fffffffffff] hotplug
[    0.424605] ACPI: SRAT: Node 1 PXM 1 [mem 0x500000000000-0x5fffffffffff] hotplug
[    0.428418] ACPI: SRAT: Node 1 PXM 1 [mem 0xa00000000000-0xbfffffffffff] hotplug
[    0.432219] ACPI: SRAT: Node 1 PXM 1 [mem 0x1400000000000-0x17fffffffffff] hotplug
[    0.436144] ACPI: SRAT: Node 1 PXM 1 [mem 0x2800000000000-0x2ffffffffffff] hotplug
[    0.440024] ACPI: SRAT: Node 1 PXM 1 [mem 0x5000000000000-0x5ffffffffffff] hotplug
[    0.443898] ACPI: SRAT: Node 1 PXM 1 [mem 0xa000000000000-0xbffffffffffff] hotplug
[    0.447794] ACPI: SRAT: Node 2 PXM 2 [mem 0xef60000000-0xf62fffffff] hotplug
[    0.451477] ACPI: SRAT: Node 2 PXM 2 [mem 0x31000000000-0x387ffffffff] hotplug
[    0.455216] ACPI: SRAT: Node 2 PXM 2 [mem 0x60000000000-0x6ffffffffff] hotplug
[    0.459041] ACPI: SRAT: Node 2 PXM 2 [mem 0xc0000000000-0xdffffffffff] hotplug
[    0.462732] ACPI: SRAT: Node 2 PXM 2 [mem 0x180000000000-0x1bffffffffff] hotplug
[    0.466547] ACPI: SRAT: Node 2 PXM 2 [mem 0x300000000000-0x37ffffffffff] hotplug
[    0.470783] ACPI: SRAT: Node 2 PXM 2 [mem 0x600000000000-0x6fffffffffff] hotplug
[    0.474591] ACPI: SRAT: Node 2 PXM 2 [mem 0xc00000000000-0xdfffffffffff] hotplug
[    0.478381] ACPI: SRAT: Node 2 PXM 2 [mem 0x1800000000000-0x1bfffffffffff] hotplug
[    0.482284] ACPI: SRAT: Node 2 PXM 2 [mem 0x3000000000000-0x37fffffffffff] hotplug
[    0.486384] ACPI: SRAT: Node 2 PXM 2 [mem 0x6000000000000-0x6ffffffffffff] hotplug
[    0.490263] ACPI: SRAT: Node 2 PXM 2 [mem 0xc000000000000-0xdffffffffffff] hotplug
[    0.494232] ACPI: SRAT: Node 3 PXM 3 [mem 0xf630000000-0xfcffffffff] hotplug
[    0.497947] ACPI: SRAT: Node 3 PXM 3 [mem 0x38800000000-0x3ffffffffff] hotplug
[    0.501889] ACPI: SRAT: Node 3 PXM 3 [mem 0x70000000000-0x7ffffffffff] hotplug
[    0.505695] ACPI: SRAT: Node 3 PXM 3 [mem 0xe0000000000-0xfffffffffff] hotplug
[    0.509560] ACPI: SRAT: Node 3 PXM 3 [mem 0x1c0000000000-0x1fffffffffff] hotplug
[    0.513563] ACPI: SRAT: Node 3 PXM 3 [mem 0x380000000000-0x3fffffffffff] hotplug
[    0.517475] ACPI: SRAT: Node 3 PXM 3 [mem 0x700000000000-0x7fffffffffff] hotplug
[    0.521308] ACPI: SRAT: Node 3 PXM 3 [mem 0xe00000000000-0xffffffffffff] hotplug
[    0.525152] ACPI: SRAT: Node 3 PXM 3 [mem 0x1c00000000000-0x1ffffffffffff] hotplug
[    0.529072] ACPI: SRAT: Node 3 PXM 3 [mem 0x3800000000000-0x3ffffffffffff] hotplug
[    0.533030] ACPI: SRAT: Node 3 PXM 3 [mem 0x7000000000000-0x7ffffffffffff] hotplug
[    0.536979] ACPI: SRAT: Node 3 PXM 3 [mem 0xe000000000000-0xfffffffffffff] hotplug
[    0.540855] NUMA: Initialized distance table, cnt=4
[    0.540861] NUMA: Node 0 [mem 0x00000000-0x3fffffff] + [mem 0x100000000-0x38ffffffff] -> [mem 0x00000000-0x38ffffffff]
[    0.546508] NODE_DATA(0) allocated [mem 0x38fffd6000-0x38ffffffff]
[    0.549806] NODE_DATA(1) allocated [mem 0x713ffd6000-0x713fffffff]
[    0.553080] NODE_DATA(2) allocated [mem 0xa97ffd6000-0xa97fffffff]
[    0.556298] NODE_DATA(3) allocated [mem 0xe1bffd4000-0xe1bfffdfff]
[    0.560779] Zone ranges:
[    0.562125]   DMA      [mem 0x0000000000001000-0x0000000000ffffff]
[    0.565406]   DMA32    [mem 0x0000000001000000-0x00000000ffffffff]
[    0.568685]   Normal   [mem 0x0000000100000000-0x000000e1bfffffff]
[    0.571929]   Device   empty
[    0.573428] Movable zone start for each node
[    0.575663] Early memory node ranges
[    0.577542]   node   0: [mem 0x0000000000001000-0x000000000009ffff]
[    0.580821]   node   0: [mem 0x0000000000100000-0x000000003ff40fff]
[    0.584056]   node   0: [mem 0x000000003ffff000-0x000000003fffffff]
[    0.587352]   node   0: [mem 0x0000000100000000-0x00000038ffffffff]
[    0.590699]   node   1: [mem 0x0000003900000000-0x000000713fffffff]
[    0.593990]   node   2: [mem 0x0000007140000000-0x000000a97fffffff]
[    0.597561]   node   3: [mem 0x000000a980000000-0x000000e1bfffffff]
[    0.601045] Initmem setup node 0 [mem 0x0000000000001000-0x00000038ffffffff]
[    0.604728] Initmem setup node 1 [mem 0x0000003900000000-0x000000713fffffff]
[    0.608487] Initmem setup node 2 [mem 0x0000007140000000-0x000000a97fffffff]
[    0.612196] Initmem setup node 3 [mem 0x000000a980000000-0x000000e1bfffffff]
[    0.615874] On node 0, zone DMA: 1 pages in unavailable ranges
[    0.615902] On node 0, zone DMA: 96 pages in unavailable ranges
[    0.620587] On node 0, zone DMA32: 190 pages in unavailable ranges
[    2.460778] ACPI: PM-Timer IO Port: 0x408
[    2.466148] ACPI: LAPIC_NMI (acpi_id[0x01] dfl dfl lint[0x1])
[    2.469432] IOAPIC[0]: apic_id 96, version 17, address 0xfec00000, GSI 0-23
[    2.473103] ACPI: INT_SRC_OVR (bus 0 bus_irq 9 global_irq 9 high level)
[    2.476494] ACPI: Using ACPI (MADT) for SMP configuration information
[    2.479830] ACPI: SPCR: console: uart,io,0x3f8,115200
[    2.482425] smpboot: Allowing 96 CPUs, 0 hotplug CPUs
[    2.485016] PM: hibernation: Registered nosave memory: [mem 0x00000000-0x00000fff]
[    2.488864] PM: hibernation: Registered nosave memory: [mem 0x000a0000-0x000bffff]
[    2.492737] PM: hibernation: Registered nosave memory: [mem 0x000c0000-0x000fffff]
[    2.496638] PM: hibernation: Registered nosave memory: [mem 0x3ff41000-0x3ffc8fff]
[    2.500518] PM: hibernation: Registered nosave memory: [mem 0x3ffc9000-0x3fffafff]
[    2.504445] PM: hibernation: Registered nosave memory: [mem 0x3fffb000-0x3fffefff]
[    2.508303] PM: hibernation: Registered nosave memory: [mem 0x40000000-0xffffffff]
[    2.512159] [mem 0x40000000-0xffffffff] available for PCI devices
[    2.515224] Booting paravirtualized kernel on Hyper-V
[    2.517763] clocksource: refined-jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645519600211568 ns
[    2.523072] setup_percpu: NR_CPUS:8192 nr_cpumask_bits:96 nr_cpu_ids:96 nr_node_ids:4
[    2.532036] percpu: Embedded 61 pages/cpu s212992 r8192 d28672 u262144
[    2.535483] pcpu-alloc: s212992 r8192 d28672 u262144 alloc=1*2097152
[    2.535486] pcpu-alloc: [0] 00 01 02 03 04 05 06 07 [0] 08 09 10 11 12 13 14 15
[    2.535498] pcpu-alloc: [0] 16 17 18 19 20 21 22 23 [1] 24 25 26 27 28 29 30 31
[    2.535509] pcpu-alloc: [1] 32 33 34 35 36 37 38 39 [1] 40 41 42 43 44 45 46 47
[    2.535519] pcpu-alloc: [2] 48 49 50 51 52 53 54 55 [2] 56 57 58 59 60 61 62 63
[    2.535529] pcpu-alloc: [2] 64 65 66 67 68 69 70 71 [3] 72 73 74 75 76 77 78 79
[    2.535540] pcpu-alloc: [3] 80 81 82 83 84 85 86 87 [3] 88 89 90 91 92 93 94 95
[    2.535588] Hyper-V: PV spinlocks enabled
[    2.537658] PV qspinlock hash table entries: 256 (order: 0, 4096 bytes, linear)
[    2.541463] Built 4 zonelists, mobility grouping on.  Total pages: 232241433
[    2.545105] Policy zone: Normal
[    2.546693] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-5.15.0-1087-azure root=PARTUUID=576855f9-6ec4-43c3-a073-17116ff21b7b ro console=tty1 console=ttyS0 earlyprintk=ttyS0 nvme_core.io_timeout=240 panic=-1
[    2.556304] Unknown kernel command line parameters "BOOT_IMAGE=/boot/vmlinuz-5.15.0-1087-azure", will be passed to user space.
[    2.562135] printk: log_buf_len individual max cpu contribution: 4096 bytes
[    2.565662] printk: log_buf_len total cpu_extra contributions: 389120 bytes
[    2.569208] printk: log_buf_len min size: 262144 bytes
[    2.572586] printk: log_buf_len: 1048576 bytes
[    2.574865] printk: early log buf free: 244280(93%)
[    2.578484] mem auto-init: stack:off, heap alloc:on, heap free:off
[    4.230603] Memory: 928805816K/943717252K available (16392K kernel code, 4308K rwdata, 10532K rodata, 3100K init, 17008K bss, 14911176K reserved, 0K cma-reserved)
[    4.239094] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=96, Nodes=4
[    4.244384] ftrace: allocating 49034 entries in 192 pages
[    4.271030] ftrace: allocated 192 pages with 2 groups
[    4.274361] rcu: Hierarchical RCU implementation.
[    4.276811] rcu: 	RCU restricting CPUs from NR_CPUS=8192 to nr_cpu_ids=96.
[    4.280365] 	Rude variant of Tasks RCU enabled.
[    4.282710] 	Tracing variant of Tasks RCU enabled.
[    4.285244] rcu: RCU calculated value of scheduler-enlistment delay is 25 jiffies.
[    4.289198] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=96
[    4.297534] Using NULL legacy PIC
[    4.299396] NR_IRQS: 524544, nr_irqs: 1192, preallocated irqs: 0
[    4.303087] Console: colour dummy device 80x25
[    4.305771] printk: console [tty1] enabled
[    4.307958] printk: console [ttyS0] enabled
[    4.312315] printk: bootconsole [earlyser0] disabled
[    4.317825] mempolicy: Enabling automatic NUMA balancing. Configure with numa_balancing= or the kernel.numa_balancing sysctl
[    4.323544] ACPI: Core revision 20210730
[    4.325707] Failed to register legacy timer interrupt
[    4.328279] APIC: Switch to symmetric I/O mode setup
[    4.330841] Switched APIC routing to physical flat.
[    4.333509] Hyper-V: Using IPI hypercalls
[    4.335608] Hyper-V: Using enlightened APIC (xapic mode)
[    4.335865] clocksource: tsc-early: mask: 0xffffffffffffffff max_cycles: 0x233fed917ea, max_idle_ns: 440795276268 ns
[    4.344109] Calibrating delay loop (skipped), value calculated using timer frequency.. 4890.89 BogoMIPS (lpj=9781796)
[    4.348107] x86/cpu: User Mode Instruction Prevention (UMIP) activated
[    4.348107] Last level iTLB entries: 4KB 1024, 2MB 1024, 4MB 512
[    4.348107] Last level dTLB entries: 4KB 2048, 2MB 2048, 4MB 1024, 1GB 0
[    4.348107] Spectre V1 : Mitigation: usercopy/swapgs barriers and __user pointer sanitization
[    4.348107] Spectre V2 : Mitigation: Retpolines
[    4.348107] Spectre V2 : Spectre v2 / SpectreRSB mitigation: Filling RSB on context switch
[    4.348107] Spectre V2 : Spectre v2 / SpectreRSB : Filling RSB on VMEXIT
[    4.348107] RETBleed: Mitigation: untrained return thunk
[    4.348107] Speculative Store Bypass: Mitigation: Speculative Store Bypass disabled via prctl and seccomp
[    4.348107] Speculative Return Stack Overflow: IBPB-extending microcode not applied!
[    4.348107] Speculative Return Stack Overflow: WARNING: See https://kernel.org/doc/html/latest/admin-guide/hw-vuln/srso.html for mitigation options.
[    4.348107] Speculative Return Stack Overflow: Mitigation: safe RET, no microcode
[    4.348107] x86/fpu: Supporting XSAVE feature 0x001: 'x87 floating point registers'
[    4.348107] x86/fpu: Supporting XSAVE feature 0x002: 'SSE registers'
[    4.348107] x86/fpu: Supporting XSAVE feature 0x004: 'AVX registers'
[    4.348107] x86/fpu: xstate_offset[2]:  576, xstate_sizes[2]:  256
[    4.348107] x86/fpu: Enabled xstate features 0x7, context size is 832 bytes, using 'compacted' format.
[    4.348107] Freeing SMP alternatives memory: 44K
[    4.348107] pid_max: default: 98304 minimum: 768
[    4.348107] LSM: Security Framework initializing
[    4.348107] landlock: Up and running.
[    4.348107] Yama: becoming mindful.
[    4.348107] AppArmor: AppArmor initialized
[    4.348107] Dentry cache hash table entries: 33554432 (order: 16, 268435456 bytes, vmalloc)
[    4.348107] Inode-cache hash table entries: 16777216 (order: 15, 134217728 bytes, vmalloc)
[    4.348107] Mount-cache hash table entries: 524288 (order: 10, 4194304 bytes, vmalloc)
[    4.348107] Mountpoint-cache hash table entries: 524288 (order: 10, 4194304 bytes, vmalloc)
[    4.348107] smpboot: CPU0: AMD EPYC 7V12 64-Core Processor (family: 0x17, model: 0x31, stepping: 0x0)
[    4.348444] Performance Events: Fam17h+ core perfctr, AMD PMU driver.
[    4.351819] ... version:                0
[    4.352112] ... bit width:              48
[    4.354251] ... generic registers:      6
[    4.356110] ... value mask:             0000ffffffffffff
[    4.358901] ... max period:             00007fffffffffff
[    4.360110] ... fixed-purpose events:   0
[    4.362163] ... event mask:             000000000000003f
[    4.364295] signal: max sigframe size: 1776
[    4.366484] rcu: Hierarchical SRCU implementation.
[    4.368648] NMI watchdog: Enabled. Permanently consumes one hw-PMU counter.
[    4.373088] smp: Bringing up secondary CPUs ...
[    4.375636] x86: Booting SMP configuration:
[    4.376112] .... node  #0, CPUs:        #1  #2  #3  #4  #5  #6  #7  #8  #9 #10 #11 #12 #13 #14 #15 #16 #17 #18 #19 #20 #21 #22 #23
[    4.392112] .... node  #1, CPUs:   #24 #25 #26 #27 #28 #29 #30 #31 #32 #33 #34 #35 #36 #37 #38 #39 #40 #41 #42 #43 #44 #45 #46 #47
[    4.412112] .... node  #2, CPUs:   #48 #49 #50 #51 #52 #53 #54 #55 #56 #57 #58 #59 #60 #61 #62 #63 #64 #65 #66 #67 #68 #69 #70 #71
[    4.512112] .... node  #3, CPUs:   #72 #73 #74 #75 #76 #77 #78 #79 #80 #81 #82 #83 #84 #85 #86 #87 #88 #89 #90 #91 #92 #93 #94 #95
[    4.532278] smp: Brought up 4 nodes, 96 CPUs
[    4.538306] smpboot: Max logical packages: 2
[    4.540120] smpboot: Total of 96 processors activated (469798.80 BogoMIPS)
[    4.641621] devtmpfs: initialized
[    4.642106] x86/mm: Memory block size: 1024MB
[    4.658193] ACPI: PM: Registering ACPI NVS region [mem 0x3fffb000-0x3fffefff] (16384 bytes)
[    4.660256] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645041785100000 ns
[    4.664359] futex hash table entries: 32768 (order: 9, 2097152 bytes, vmalloc)
[    4.668484] pinctrl core: initialized pinctrl subsystem
[    4.671746] PM: RTC time: 20:51:00, date: 2025-05-10
[    4.673103] NET: Registered PF_NETLINK/PF_ROUTE protocol family
[    4.676572] DMA: preallocated 4096 KiB GFP_KERNEL pool for atomic allocations
[    4.680352] DMA: preallocated 4096 KiB GFP_KERNEL|GFP_DMA pool for atomic allocations
[    4.684353] DMA: preallocated 4096 KiB GFP_KERNEL|GFP_DMA32 pool for atomic allocations
[    4.688125] audit: initializing netlink subsys (disabled)
[    4.690998] audit: type=2000 audit(1746910259.344:1): state=initialized audit_enabled=0 res=1
[    4.690998] thermal_sys: Registered thermal governor 'fair_share'
[    4.692112] thermal_sys: Registered thermal governor 'bang_bang'
[    4.695320] thermal_sys: Registered thermal governor 'step_wise'
[    4.696110] thermal_sys: Registered thermal governor 'user_space'
[    4.699259] thermal_sys: Registered thermal governor 'power_allocator'
[    4.700120] EISA bus registered
[    4.704164] cpuidle: using governor ladder
[    4.704291] cpuidle: using governor menu
[    4.708249] ACPI: bus type PCI registered
[    4.712112] acpiphp: ACPI Hot Plug PCI Controller Driver version: 0.5
[    4.724203] kprobes: kprobe jump-optimization is enabled. All kprobes are optimized if possible.
[    4.728201] HugeTLB registered 1.00 GiB page size, pre-allocated 0 pages
[    4.732112] HugeTLB registered 2.00 MiB page size, pre-allocated 0 pages
[    4.740266] ACPI: Added _OSI(Module Device)
[    4.742422] ACPI: Added _OSI(Processor Device)
[    4.744115] ACPI: Added _OSI(3.0 _SCP Extensions)
[    4.746549] ACPI: Added _OSI(Processor Aggregator Device)
[    4.748111] ACPI: Added _OSI(Linux-Dell-Video)
[    4.750395] ACPI: Added _OSI(Linux-Lenovo-NV-HDMI-Audio)
[    4.752111] ACPI: Added _OSI(Linux-HPI-Hybrid-Graphics)
[    4.784637] ACPI: 1 ACPI AML tables successfully acquired and loaded
[    4.791908] ACPI: Interpreter enabled
[    4.792134] ACPI: PM: (supports S0 S5)
[    4.794088] ACPI: Using IOAPIC for interrupt routing
[    4.796129] PCI: Using host bridge windows from ACPI; if necessary, use "pci=nocrs" and report a bug
[    4.800110] PCI: Using E820 reservations for host bridge windows
[    4.804922] ACPI: Enabled 1 GPEs in block 00 to 0F
[    4.817689] iommu: Default domain type: Translated
[    4.820112] iommu: DMA domain TLB invalidation policy: lazy mode
[    4.823533] SCSI subsystem initialized
[    4.824169] libata version 3.00 loaded.
[    4.824169] vgaarb: loaded
[    4.825594] ACPI: bus type USB registered
[    4.827740] usbcore: registered new interface driver usbfs
[    4.828123] usbcore: registered new interface driver hub
[    4.831057] usbcore: registered new device driver usb
[    4.832128] pps_core: LinuxPPS API ver. 1 registered
[    4.834699] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[    4.836113] PTP clock support registered
[    4.838213] EDAC MC: Ver: 3.0.0
[    4.840145] Registered efivars operations
[    4.848178] hv_vmbus: Vmbus version:5.2
[    4.852762] NetLabel: Initializing
[    4.854249] NetLabel:  domain hash size = 128
[    4.856111] NetLabel:  protocols = UNLABELED CIPSOv4 CALIPSO
[    4.859081] NetLabel:  unlabeled traffic allowed by default
[    4.860175] PCI: Using ACPI for IRQ routing
[    4.862352] PCI: System does not support PCI
[    4.864778] clocksource: Switched to clocksource tsc-early
[    4.890642] VFS: Disk quotas dquot_6.6.0
[    4.892816] VFS: Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
[    4.896691] AppArmor: AppArmor Filesystem Enabled
[    4.899196] pnp: PnP ACPI init
[    4.902098] pnp: PnP ACPI: found 3 devices
[    4.912027] clocksource: acpi_pm: mask: 0xffffff max_cycles: 0xffffff, max_idle_ns: 2085701024 ns
[    4.916850] NET: Registered PF_INET protocol family
[    4.919663] IP idents hash table entries: 262144 (order: 9, 2097152 bytes, vmalloc)
[    4.925298] tcp_listen_portaddr_hash hash table entries: 65536 (order: 8, 1048576 bytes, vmalloc)
[    4.929989] Table-perturb hash table entries: 65536 (order: 6, 262144 bytes, vmalloc)
[    4.934602] TCP established hash table entries: 524288 (order: 10, 4194304 bytes, vmalloc)
[    4.939457] TCP bind hash table entries: 65536 (order: 8, 1048576 bytes, vmalloc)
[    4.943455] TCP: Hash tables configured (established 524288 bind 65536)
[    4.947392] MPTCP token hash table entries: 65536 (order: 8, 1572864 bytes, vmalloc)
[    4.951764] UDP hash table entries: 65536 (order: 9, 2097152 bytes, vmalloc)
[    4.955938] UDP-Lite hash table entries: 65536 (order: 9, 2097152 bytes, vmalloc)
[    4.960168] NET: Registered PF_UNIX/PF_LOCAL protocol family
[    4.963145] NET: Registered PF_XDP protocol family
[    4.965671] PCI: CLS 0 bytes, default 64
[    4.967719] PCI-DMA: Using software bounce buffering for IO (SWIOTLB)
[    4.971028] software IO TLB: mapped [mem 0x000000003a95d000-0x000000003e95d000] (64MB)
[    4.975266] clocksource: tsc: mask: 0xffffffffffffffff max_cycles: 0x233fed917ea, max_idle_ns: 440795276268 ns
[    4.980979] clocksource: Switched to clocksource tsc
[    4.986585] Initialise system trusted keyrings
[    4.988960] Key type blacklist registered
[    4.991457] workingset: timestamp_bits=36 max_order=28 bucket_order=0
[    4.997298] zbud: loaded
[    4.999617] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    5.003060] fuse: init (API version 7.34)
[    5.006378] integrity: Platform Keyring initialized
[    5.012929] Key type asymmetric registered
[    5.015201] Asymmetric key parser 'x509' registered
[    5.017829] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 244)
[    5.021858] io scheduler mq-deadline registered
[    5.028052] shpchp: Standard Hot Plug PCI Controller Driver version: 0.4
[    5.031663] hv_vmbus: registering driver hv_pci
[    5.034510] hv_pci 0000000b-0101-0001-3135-423331303142: PCI VMBus probing: Using version 0x10004
[    5.040621] hv_pci 0000000b-0101-0001-3135-423331303142: PCI host bridge to bus 0101:00
[    5.044887] pci_bus 0101:00: root bus resource [mem 0x10000000000-0x10001ffffff window]
[    5.049079] pci_bus 0101:00: No busn resource found for root bus, will use [bus 00-ff]
[    5.054999] pci 0101:00:00.0: [15b3:101c] type 00 class 0x020700
[    5.060510] pci 0101:00:00.0: reg 0x10: [mem 0x10000000000-0x10001ffffff 64bit pref]
[    5.066486] pci 0101:00:00.0: enabling Extended Tags
[    5.078728] pci 0101:00:00.0: 0.000 Gb/s available PCIe bandwidth, limited by Unknown x0 link at 0101:00:00.0 (capable of 252.048 Gb/s with 16.0 GT/s PCIe x16 link)
[    5.092958] pci_bus 0101:00: busn_res: [bus 00-ff] end is updated to 00
[    5.096529] pci 0101:00:00.0: BAR 0: assigned [mem 0x10000000000-0x10001ffffff 64bit pref]
[    5.102504] hv_pci 00000015-0102-0001-3135-423331303142: PCI VMBus probing: Using version 0x10004
[    5.108511] hv_pci 00000015-0102-0001-3135-423331303142: PCI host bridge to bus 0102:00
[    5.112797] pci_bus 0102:00: root bus resource [mem 0x10002000000-0x10003ffffff window]
[    5.117002] pci_bus 0102:00: No busn resource found for root bus, will use [bus 00-ff]
[    5.122863] pci 0102:00:00.0: [15b3:101c] type 00 class 0x020700
[    5.128476] pci 0102:00:00.0: reg 0x10: [mem 0x10002000000-0x10003ffffff 64bit pref]
[    5.134507] pci 0102:00:00.0: enabling Extended Tags
[    5.146808] pci 0102:00:00.0: 0.000 Gb/s available PCIe bandwidth, limited by Unknown x0 link at 0102:00:00.0 (capable of 252.048 Gb/s with 16.0 GT/s PCIe x16 link)
[    5.161014] pci_bus 0102:00: busn_res: [bus 00-ff] end is updated to 00
[    5.164697] pci 0102:00:00.0: BAR 0: assigned [mem 0x10002000000-0x10003ffffff 64bit pref]
[    5.170746] hv_pci 0000004b-0103-0000-3135-423331303142: PCI VMBus probing: Using version 0x10004
[    5.176738] hv_pci 0000004b-0103-0000-3135-423331303142: PCI host bridge to bus 0103:00
[    5.180960] pci_bus 0103:00: root bus resource [mem 0x10004000000-0x10005ffffff window]
[    5.185166] pci_bus 0103:00: No busn resource found for root bus, will use [bus 00-ff]
[    5.191296] pci 0103:00:00.0: [15b3:101c] type 00 class 0x020700
[    5.196984] pci 0103:00:00.0: reg 0x10: [mem 0x10004000000-0x10005ffffff 64bit pref]
[    5.203155] pci 0103:00:00.0: enabling Extended Tags
[    5.216530] pci 0103:00:00.0: 0.000 Gb/s available PCIe bandwidth, limited by Unknown x0 link at 0103:00:00.0 (capable of 252.048 Gb/s with 16.0 GT/s PCIe x16 link)
[    5.230913] pci_bus 0103:00: busn_res: [bus 00-ff] end is updated to 00
[    5.234491] pci 0103:00:00.0: BAR 0: assigned [mem 0x10004000000-0x10005ffffff 64bit pref]
[    5.240571] hv_pci 00000055-0104-0000-3135-423331303142: PCI VMBus probing: Using version 0x10004
[    5.246467] hv_pci 00000055-0104-0000-3135-423331303142: PCI host bridge to bus 0104:00
[    5.250724] pci_bus 0104:00: root bus resource [mem 0x10006000000-0x10007ffffff window]
[    5.255057] pci_bus 0104:00: No busn resource found for root bus, will use [bus 00-ff]
[    5.261324] pci 0104:00:00.0: [15b3:101c] type 00 class 0x020700
[    5.266989] pci 0104:00:00.0: reg 0x10: [mem 0x10006000000-0x10007ffffff 64bit pref]
[    5.273222] pci 0104:00:00.0: enabling Extended Tags
[    5.287405] pci 0104:00:00.0: 0.000 Gb/s available PCIe bandwidth, limited by Unknown x0 link at 0104:00:00.0 (capable of 252.048 Gb/s with 16.0 GT/s PCIe x16 link)
[    5.301669] pci_bus 0104:00: busn_res: [bus 00-ff] end is updated to 00
[    5.305207] pci 0104:00:00.0: BAR 0: assigned [mem 0x10006000000-0x10007ffffff 64bit pref]
[    5.311335] hv_pci 0000008b-0105-0003-3135-423331303142: PCI VMBus probing: Using version 0x10004
[    5.317314] hv_pci 0000008b-0105-0003-3135-423331303142: PCI host bridge to bus 0105:00
[    5.321569] pci_bus 0105:00: root bus resource [mem 0x10008000000-0x10009ffffff window]
[    5.325833] pci_bus 0105:00: No busn resource found for root bus, will use [bus 00-ff]
[    5.331971] pci 0105:00:00.0: [15b3:101c] type 00 class 0x020700
[    5.337684] pci 0105:00:00.0: reg 0x10: [mem 0x10008000000-0x10009ffffff 64bit pref]
[    5.343841] pci 0105:00:00.0: enabling Extended Tags
[    5.357268] pci 0105:00:00.0: 0.000 Gb/s available PCIe bandwidth, limited by Unknown x0 link at 0105:00:00.0 (capable of 252.048 Gb/s with 16.0 GT/s PCIe x16 link)
[    5.371743] pci_bus 0105:00: busn_res: [bus 00-ff] end is updated to 00
[    5.375422] pci 0105:00:00.0: BAR 0: assigned [mem 0x10008000000-0x10009ffffff 64bit pref]
[    5.381502] hv_pci 00000095-0106-0003-3135-423331303142: PCI VMBus probing: Using version 0x10004
[    5.387389] hv_pci 00000095-0106-0003-3135-423331303142: PCI host bridge to bus 0106:00
[    5.391662] pci_bus 0106:00: root bus resource [mem 0x1000a000000-0x1000bffffff window]
[    5.396046] pci_bus 0106:00: No busn resource found for root bus, will use [bus 00-ff]
[    5.402077] pci 0106:00:00.0: [15b3:101c] type 00 class 0x020700
[    5.407766] pci 0106:00:00.0: reg 0x10: [mem 0x1000a000000-0x1000bffffff 64bit pref]
[    5.414024] pci 0106:00:00.0: enabling Extended Tags
[    5.427355] pci 0106:00:00.0: 0.000 Gb/s available PCIe bandwidth, limited by Unknown x0 link at 0106:00:00.0 (capable of 252.048 Gb/s with 16.0 GT/s PCIe x16 link)
[    5.441758] pci_bus 0106:00: busn_res: [bus 00-ff] end is updated to 00
[    5.445680] pci 0106:00:00.0: BAR 0: assigned [mem 0x1000a000000-0x1000bffffff 64bit pref]
[    5.451954] hv_pci 000000cb-0107-0002-3135-423331303142: PCI VMBus probing: Using version 0x10004
[    5.459235] hv_pci 000000cb-0107-0002-3135-423331303142: PCI host bridge to bus 0107:00
[    5.463529] pci_bus 0107:00: root bus resource [mem 0x1000c000000-0x1000dffffff window]
[    5.467810] pci_bus 0107:00: No busn resource found for root bus, will use [bus 00-ff]
[    5.474103] pci 0107:00:00.0: [15b3:101c] type 00 class 0x020700
[    5.480041] pci 0107:00:00.0: reg 0x10: [mem 0x1000c000000-0x1000dffffff 64bit pref]
[    5.486294] pci 0107:00:00.0: enabling Extended Tags
[    5.499777] pci 0107:00:00.0: 0.000 Gb/s available PCIe bandwidth, limited by Unknown x0 link at 0107:00:00.0 (capable of 252.048 Gb/s with 16.0 GT/s PCIe x16 link)
[    5.514465] pci_bus 0107:00: busn_res: [bus 00-ff] end is updated to 00
[    5.518084] pci 0107:00:00.0: BAR 0: assigned [mem 0x1000c000000-0x1000dffffff 64bit pref]
[    5.524226] hv_pci 000000d5-0108-0002-3135-423331303142: PCI VMBus probing: Using version 0x10004
[    5.530281] hv_pci 000000d5-0108-0002-3135-423331303142: PCI host bridge to bus 0108:00
[    5.534579] pci_bus 0108:00: root bus resource [mem 0x1000e000000-0x1000fffffff window]
[    5.538930] pci_bus 0108:00: No busn resource found for root bus, will use [bus 00-ff]
[    5.545071] pci 0108:00:00.0: [15b3:101c] type 00 class 0x020700
[    5.550828] pci 0108:00:00.0: reg 0x10: [mem 0x1000e000000-0x1000fffffff 64bit pref]
[    5.557100] pci 0108:00:00.0: enabling Extended Tags
[    5.570717] pci 0108:00:00.0: 0.000 Gb/s available PCIe bandwidth, limited by Unknown x0 link at 0108:00:00.0 (capable of 252.048 Gb/s with 16.0 GT/s PCIe x16 link)
[    5.585215] pci_bus 0108:00: busn_res: [bus 00-ff] end is updated to 00
[    5.588826] pci 0108:00:00.0: BAR 0: assigned [mem 0x1000e000000-0x1000fffffff 64bit pref]
[    5.594941] hv_pci 0000000e-0001-0001-3130-444500000000: PCI VMBus probing: Using version 0x10004
[    5.600541] hv_pci 0000000e-0001-0001-3130-444500000000: PCI host bridge to bus 0001:00
[    5.604851] pci_bus 0001:00: root bus resource [mem 0x41000000-0x41ffffff window]
[    5.608897] pci_bus 0001:00: root bus resource [mem 0x11000000000-0x12001ffffff window]
[    5.613198] pci_bus 0001:00: No busn resource found for root bus, will use [bus 00-ff]
[    5.619615] pci 0001:00:00.0: [10de:20b0] type 00 class 0x030200
[    5.623571] pci 0001:00:00.0: reg 0x10: [mem 0x41000000-0x41ffffff]
[    5.627570] pci 0001:00:00.0: reg 0x14: [mem 0x11000000000-0x11fffffffff 64bit pref]
[    5.632265] pci 0001:00:00.0: reg 0x1c: [mem 0x12000000000-0x12001ffffff 64bit pref]
[    5.637543] pci 0001:00:00.0: Enabling HDA controller
[    5.646410] pci 0001:00:00.0: PME# supported from D0 D3hot
[    5.666102] pci_bus 0001:00: busn_res: [bus 00-ff] end is updated to 00
[    5.669709] pci 0001:00:00.0: BAR 1: assigned [mem 0x11000000000-0x11fffffffff 64bit pref]
[    5.674595] pci 0001:00:00.0: BAR 3: assigned [mem 0x12000000000-0x12001ffffff 64bit pref]
[    5.679497] pci 0001:00:00.0: BAR 0: assigned [mem 0x41000000-0x41ffffff]
[    5.684097] hv_pci 00000013-0002-0001-3130-444500000000: PCI VMBus probing: Using version 0x10004
[    5.689635] hv_pci 00000013-0002-0001-3130-444500000000: PCI host bridge to bus 0002:00
[    5.693867] pci_bus 0002:00: root bus resource [mem 0x42000000-0x42ffffff window]
[    5.697852] pci_bus 0002:00: root bus resource [mem 0x13000000000-0x14001ffffff window]
[    5.702053] pci_bus 0002:00: No busn resource found for root bus, will use [bus 00-ff]
[    5.708393] pci 0002:00:00.0: [10de:20b0] type 00 class 0x030200
[    5.712429] pci 0002:00:00.0: reg 0x10: [mem 0x42000000-0x42ffffff]
[    5.716374] pci 0002:00:00.0: reg 0x14: [mem 0x13000000000-0x13fffffffff 64bit pref]
[    5.721071] pci 0002:00:00.0: reg 0x1c: [mem 0x14000000000-0x14001ffffff 64bit pref]
[    5.726241] pci 0002:00:00.0: Enabling HDA controller
[    5.735120] pci 0002:00:00.0: PME# supported from D0 D3hot
[    5.753554] pci_bus 0002:00: busn_res: [bus 00-ff] end is updated to 00
[    5.757062] pci 0002:00:00.0: BAR 1: assigned [mem 0x13000000000-0x13fffffffff 64bit pref]
[    5.761992] pci 0002:00:00.0: BAR 3: assigned [mem 0x14000000000-0x14001ffffff 64bit pref]
[    5.766791] pci 0002:00:00.0: BAR 0: assigned [mem 0x42000000-0x42ffffff]
[    5.771264] hv_pci 0000004e-0003-0000-3130-444500000000: PCI VMBus probing: Using version 0x10004
[    5.776812] hv_pci 0000004e-0003-0000-3130-444500000000: PCI host bridge to bus 0003:00
[    5.781083] pci_bus 0003:00: root bus resource [mem 0x43000000-0x43ffffff window]
[    5.785033] pci_bus 0003:00: root bus resource [mem 0x15000000000-0x16001ffffff window]
[    5.789295] pci_bus 0003:00: No busn resource found for root bus, will use [bus 00-ff]
[    5.795729] pci 0003:00:00.0: [10de:20b0] type 00 class 0x030200
[    5.799680] pci 0003:00:00.0: reg 0x10: [mem 0x43000000-0x43ffffff]
[    5.803562] pci 0003:00:00.0: reg 0x14: [mem 0x15000000000-0x15fffffffff 64bit pref]
[    5.808274] pci 0003:00:00.0: reg 0x1c: [mem 0x16000000000-0x16001ffffff 64bit pref]
[    5.813518] pci 0003:00:00.0: Enabling HDA controller
[    5.822402] pci 0003:00:00.0: PME# supported from D0 D3hot
[    5.843006] pci_bus 0003:00: busn_res: [bus 00-ff] end is updated to 00
[    5.846607] pci 0003:00:00.0: BAR 1: assigned [mem 0x15000000000-0x15fffffffff 64bit pref]
[    5.851480] pci 0003:00:00.0: BAR 3: assigned [mem 0x16000000000-0x16001ffffff 64bit pref]
[    5.856536] pci 0003:00:00.0: BAR 0: assigned [mem 0x43000000-0x43ffffff]
[    5.861145] hv_pci 00000053-0004-0000-3130-444500000000: PCI VMBus probing: Using version 0x10004
[    5.866726] hv_pci 00000053-0004-0000-3130-444500000000: PCI host bridge to bus 0004:00
[    5.870966] pci_bus 0004:00: root bus resource [mem 0x44000000-0x44ffffff window]
[    5.874913] pci_bus 0004:00: root bus resource [mem 0x17000000000-0x18001ffffff window]
[    5.879173] pci_bus 0004:00: No busn resource found for root bus, will use [bus 00-ff]
[    5.885493] pci 0004:00:00.0: [10de:20b0] type 00 class 0x030200
[    5.889569] pci 0004:00:00.0: reg 0x10: [mem 0x44000000-0x44ffffff]
[    5.893537] pci 0004:00:00.0: reg 0x14: [mem 0x17000000000-0x17fffffffff 64bit pref]
[    5.898264] pci 0004:00:00.0: reg 0x1c: [mem 0x18000000000-0x18001ffffff 64bit pref]
[    5.903584] pci 0004:00:00.0: Enabling HDA controller
[    5.912575] pci 0004:00:00.0: PME# supported from D0 D3hot
[    5.930916] pci_bus 0004:00: busn_res: [bus 00-ff] end is updated to 00
[    5.934560] pci 0004:00:00.0: BAR 1: assigned [mem 0x17000000000-0x17fffffffff 64bit pref]
[    5.939497] pci 0004:00:00.0: BAR 3: assigned [mem 0x18000000000-0x18001ffffff 64bit pref]
[    5.944360] pci 0004:00:00.0: BAR 0: assigned [mem 0x44000000-0x44ffffff]
[    5.948875] hv_pci 00000065-0005-0000-3130-444500000000: PCI VMBus probing: Using version 0x10004
[    5.954223] hv_pci 00000065-0005-0000-3130-444500000000: PCI host bridge to bus 0005:00
[    5.958442] pci_bus 0005:00: root bus resource [mem 0x46000000-0x47ffffff window]
[    5.962507] pci_bus 0005:00: No busn resource found for root bus, will use [bus 00-ff]
[    5.968244] pci 0005:00:00.0: [10de:1af1] type 00 class 0x068000
[    5.972231] pci 0005:00:00.0: reg 0x10: [mem 0x46000000-0x47ffffff]
[    5.982445] pci 0005:00:00.0: PME# supported from D0 D3hot
[    5.997715] pci_bus 0005:00: busn_res: [bus 00-ff] end is updated to 00
[    6.001278] pci 0005:00:00.0: BAR 0: assigned [mem 0x46000000-0x47ffffff]
[    6.005619] hv_pci 00000066-0006-0000-3130-444500000000: PCI VMBus probing: Using version 0x10004
[    6.010989] hv_pci 00000066-0006-0000-3130-444500000000: PCI host bridge to bus 0006:00
[    6.015269] pci_bus 0006:00: root bus resource [mem 0x48000000-0x49ffffff window]
[    6.019238] pci_bus 0006:00: No busn resource found for root bus, will use [bus 00-ff]
[    6.024949] pci 0006:00:00.0: [10de:1af1] type 00 class 0x068000
[    6.028895] pci 0006:00:00.0: reg 0x10: [mem 0x48000000-0x49ffffff]
[    6.040881] pci 0006:00:00.0: PME# supported from D0 D3hot
[    6.056319] pci_bus 0006:00: busn_res: [bus 00-ff] end is updated to 00
[    6.059842] pci 0006:00:00.0: BAR 0: assigned [mem 0x48000000-0x49ffffff]
[    6.064349] hv_pci 00000067-0007-0000-3130-444500000000: PCI VMBus probing: Using version 0x10004
[    6.069625] hv_pci 00000067-0007-0000-3130-444500000000: PCI host bridge to bus 0007:00
[    6.073872] pci_bus 0007:00: root bus resource [mem 0x4a000000-0x4bffffff window]
[    6.077860] pci_bus 0007:00: No busn resource found for root bus, will use [bus 00-ff]
[    6.083594] pci 0007:00:00.0: [10de:1af1] type 00 class 0x068000
[    6.087564] pci 0007:00:00.0: reg 0x10: [mem 0x4a000000-0x4bffffff]
[    6.097755] pci 0007:00:00.0: PME# supported from D0 D3hot
[    6.113179] pci_bus 0007:00: busn_res: [bus 00-ff] end is updated to 00
[    6.116864] pci 0007:00:00.0: BAR 0: assigned [mem 0x4a000000-0x4bffffff]
[    6.121317] hv_pci 00000068-0008-0000-3130-444500000000: PCI VMBus probing: Using version 0x10004
[    6.126702] hv_pci 00000068-0008-0000-3130-444500000000: PCI host bridge to bus 0008:00
[    6.131020] pci_bus 0008:00: root bus resource [mem 0x4c000000-0x4dffffff window]
[    6.134996] pci_bus 0008:00: No busn resource found for root bus, will use [bus 00-ff]
[    6.140760] pci 0008:00:00.0: [10de:1af1] type 00 class 0x068000
[    6.144767] pci 0008:00:00.0: reg 0x10: [mem 0x4c000000-0x4dffffff]
[    6.154867] pci 0008:00:00.0: PME# supported from D0 D3hot
[    6.170179] pci_bus 0008:00: busn_res: [bus 00-ff] end is updated to 00
[    6.173783] pci 0008:00:00.0: BAR 0: assigned [mem 0x4c000000-0x4dffffff]
[    6.178228] hv_pci 00000069-0009-0000-3130-444500000000: PCI VMBus probing: Using version 0x10004
[    6.184739] hv_pci 00000069-0009-0000-3130-444500000000: PCI host bridge to bus 0009:00
[    6.188997] pci_bus 0009:00: root bus resource [mem 0x4e000000-0x4fffffff window]
[    6.193051] pci_bus 0009:00: No busn resource found for root bus, will use [bus 00-ff]
[    6.198789] pci 0009:00:00.0: [10de:1af1] type 00 class 0x068000
[    6.202774] pci 0009:00:00.0: reg 0x10: [mem 0x4e000000-0x4fffffff]
[    6.214384] pci 0009:00:00.0: PME# supported from D0 D3hot
[    6.229713] pci_bus 0009:00: busn_res: [bus 00-ff] end is updated to 00
[    6.233406] pci 0009:00:00.0: BAR 0: assigned [mem 0x4e000000-0x4fffffff]
[    6.237792] hv_pci 0000006a-000a-0000-3130-444500000000: PCI VMBus probing: Using version 0x10004
[    6.243067] hv_pci 0000006a-000a-0000-3130-444500000000: PCI host bridge to bus 000a:00
[    6.247304] pci_bus 000a:00: root bus resource [mem 0x50000000-0x51ffffff window]
[    6.251249] pci_bus 000a:00: No busn resource found for root bus, will use [bus 00-ff]
[    6.257144] pci 000a:00:00.0: [10de:1af1] type 00 class 0x068000
[    6.261086] pci 000a:00:00.0: reg 0x10: [mem 0x50000000-0x51ffffff]
[    6.271338] pci 000a:00:00.0: PME# supported from D0 D3hot
[    6.286635] pci_bus 000a:00: busn_res: [bus 00-ff] end is updated to 00
[    6.290194] pci 000a:00:00.0: BAR 0: assigned [mem 0x50000000-0x51ffffff]
[    6.294622] hv_pci 0000008e-000b-0003-3130-444500000000: PCI VMBus probing: Using version 0x10004
[    6.300115] hv_pci 0000008e-000b-0003-3130-444500000000: PCI host bridge to bus 000b:00
[    6.304573] pci_bus 000b:00: root bus resource [mem 0x45000000-0x45ffffff window]
[    6.308525] pci_bus 000b:00: root bus resource [mem 0x19000000000-0x1a001ffffff window]
[    6.312813] pci_bus 000b:00: No busn resource found for root bus, will use [bus 00-ff]
[    6.319225] pci 000b:00:00.0: [10de:20b0] type 00 class 0x030200
[    6.323337] pci 000b:00:00.0: reg 0x10: [mem 0x45000000-0x45ffffff]
[    6.327329] pci 000b:00:00.0: reg 0x14: [mem 0x19000000000-0x19fffffffff 64bit pref]
[    6.332041] pci 000b:00:00.0: reg 0x1c: [mem 0x1a000000000-0x1a001ffffff 64bit pref]
[    6.337233] pci 000b:00:00.0: Enabling HDA controller
[    6.346044] pci 000b:00:00.0: PME# supported from D0 D3hot
[    6.366641] pci_bus 000b:00: busn_res: [bus 00-ff] end is updated to 00
[    6.370155] pci 000b:00:00.0: BAR 1: assigned [mem 0x19000000000-0x19fffffffff 64bit pref]
[    6.375054] pci 000b:00:00.0: BAR 3: assigned [mem 0x1a000000000-0x1a001ffffff 64bit pref]
[    6.379928] pci 000b:00:00.0: BAR 0: assigned [mem 0x45000000-0x45ffffff]
[    6.384483] hv_pci 00000094-000c-0003-3130-444500000000: PCI VMBus probing: Using version 0x10004
[    6.389994] hv_pci 00000094-000c-0003-3130-444500000000: PCI host bridge to bus 000c:00
[    6.394224] pci_bus 000c:00: root bus resource [mem 0x52000000-0x52ffffff window]
[    6.398236] pci_bus 000c:00: root bus resource [mem 0x1b000000000-0x1c001ffffff window]
[    6.402475] pci_bus 000c:00: No busn resource found for root bus, will use [bus 00-ff]
[    6.408840] pci 000c:00:00.0: [10de:20b0] type 00 class 0x030200
[    6.412865] pci 000c:00:00.0: reg 0x10: [mem 0x52000000-0x52ffffff]
[    6.416895] pci 000c:00:00.0: reg 0x14: [mem 0x1b000000000-0x1bfffffffff 64bit pref]
[    6.421560] pci 000c:00:00.0: reg 0x1c: [mem 0x1c000000000-0x1c001ffffff 64bit pref]
[    6.426859] pci 000c:00:00.0: Enabling HDA controller
[    6.435625] pci 000c:00:00.0: PME# supported from D0 D3hot
[    6.453867] pci_bus 000c:00: busn_res: [bus 00-ff] end is updated to 00
[    6.457434] pci 000c:00:00.0: BAR 1: assigned [mem 0x1b000000000-0x1bfffffffff 64bit pref]
[    6.462466] pci 000c:00:00.0: BAR 3: assigned [mem 0x1c000000000-0x1c001ffffff 64bit pref]
[    6.467960] pci 000c:00:00.0: BAR 0: assigned [mem 0x52000000-0x52ffffff]
[    6.472531] hv_pci 000000ce-000d-0002-3130-444500000000: PCI VMBus probing: Using version 0x10004
[    6.478188] hv_pci 000000ce-000d-0002-3130-444500000000: PCI host bridge to bus 000d:00
[    6.482376] pci_bus 000d:00: root bus resource [mem 0x53000000-0x53ffffff window]
[    6.486332] pci_bus 000d:00: root bus resource [mem 0x1d000000000-0x1e001ffffff window]
[    6.490533] pci_bus 000d:00: No busn resource found for root bus, will use [bus 00-ff]
[    6.496943] pci 000d:00:00.0: [10de:20b0] type 00 class 0x030200
[    6.500914] pci 000d:00:00.0: reg 0x10: [mem 0x53000000-0x53ffffff]
[    6.504897] pci 000d:00:00.0: reg 0x14: [mem 0x1d000000000-0x1dfffffffff 64bit pref]
[    6.509706] pci 000d:00:00.0: reg 0x1c: [mem 0x1e000000000-0x1e001ffffff 64bit pref]
[    6.514960] pci 000d:00:00.0: Enabling HDA controller
[    6.523879] pci 000d:00:00.0: PME# supported from D0 D3hot
[    6.542274] pci_bus 000d:00: busn_res: [bus 00-ff] end is updated to 00
[    6.545843] pci 000d:00:00.0: BAR 1: assigned [mem 0x1d000000000-0x1dfffffffff 64bit pref]
[    6.550725] pci 000d:00:00.0: BAR 3: assigned [mem 0x1e000000000-0x1e001ffffff 64bit pref]
[    6.555809] pci 000d:00:00.0: BAR 0: assigned [mem 0x53000000-0x53ffffff]
[    6.560417] hv_pci 000000d4-000e-0002-3130-444500000000: PCI VMBus probing: Using version 0x10004
[    6.565983] hv_pci 000000d4-000e-0002-3130-444500000000: PCI host bridge to bus 000e:00
[    6.570257] pci_bus 000e:00: root bus resource [mem 0x54000000-0x54ffffff window]
[    6.574390] pci_bus 000e:00: root bus resource [mem 0x1f000000000-0x20001ffffff window]
[    6.578669] pci_bus 000e:00: No busn resource found for root bus, will use [bus 00-ff]
[    6.585101] pci 000e:00:00.0: [10de:20b0] type 00 class 0x030200
[    6.589141] pci 000e:00:00.0: reg 0x10: [mem 0x54000000-0x54ffffff]
[    6.593102] pci 000e:00:00.0: reg 0x14: [mem 0x1f000000000-0x1ffffffffff 64bit pref]
[    6.597805] pci 000e:00:00.0: reg 0x1c: [mem 0x20000000000-0x20001ffffff 64bit pref]
[    6.603117] pci 000e:00:00.0: Enabling HDA controller
[    6.613440] pci 000e:00:00.0: PME# supported from D0 D3hot
[    6.631587] pci_bus 000e:00: busn_res: [bus 00-ff] end is updated to 00
[    6.635208] pci 000e:00:00.0: BAR 1: assigned [mem 0x1f000000000-0x1ffffffffff 64bit pref]
[    6.640216] pci 000e:00:00.0: BAR 3: assigned [mem 0x20000000000-0x20001ffffff 64bit pref]
[    6.645160] pci 000e:00:00.0: BAR 0: assigned [mem 0x54000000-0x54ffffff]
[    6.649750] hv_pci a14b5a13-0dcc-4414-afc5-c35945d158e3: PCI VMBus probing: Using version 0x10004
[    6.657154] hv_pci a14b5a13-0dcc-4414-afc5-c35945d158e3: PCI host bridge to bus 0dcc:00
[    6.661495] pci_bus 0dcc:00: root bus resource [mem 0x10010000000-0x1001000bfff window]
[    6.665755] pci_bus 0dcc:00: No busn resource found for root bus, will use [bus 00-ff]
[    6.671186] pci 0dcc:00:00.0: [1414:b111] type 00 class 0x010802
[    6.675471] pci 0dcc:00:00.0: reg 0x10: [mem 0x10010008000-0x1001000bfff 64bit]
[    6.680730] pci 0dcc:00:00.0: reg 0x20: [mem 0x10010000000-0x10010007fff 64bit]
[    6.700632] pci_bus 0dcc:00: busn_res: [bus 00-ff] end is updated to 00
[    6.704188] pci 0dcc:00:00.0: BAR 4: assigned [mem 0x10010000000-0x10010007fff 64bit]
[    6.708937] pci 0dcc:00:00.0: BAR 0: assigned [mem 0x10010008000-0x1001000bfff 64bit]
[    6.713940] hv_pci 2b06a674-8480-4c9b-b93f-816412f7337b: PCI VMBus probing: Using version 0x10004
[    6.721221] hv_pci 2b06a674-8480-4c9b-b93f-816412f7337b: PCI host bridge to bus 8480:00
[    6.725486] pci_bus 8480:00: root bus resource [mem 0x10010010000-0x1001001bfff window]
[    6.729765] pci_bus 8480:00: No busn resource found for root bus, will use [bus 00-ff]
[    6.735185] pci 8480:00:00.0: [1414:b111] type 00 class 0x010802
[    6.739389] pci 8480:00:00.0: reg 0x10: [mem 0x10010018000-0x1001001bfff 64bit]
[    6.744538] pci 8480:00:00.0: reg 0x20: [mem 0x10010010000-0x10010017fff 64bit]
[    6.764163] pci_bus 8480:00: busn_res: [bus 00-ff] end is updated to 00
[    6.767752] pci 8480:00:00.0: BAR 4: assigned [mem 0x10010010000-0x10010017fff 64bit]
[    6.772365] pci 8480:00:00.0: BAR 0: assigned [mem 0x10010018000-0x1001001bfff 64bit]
[    6.777301] hv_pci 9e6a0d4a-8fda-40ae-97cb-94679217f071: PCI VMBus probing: Using version 0x10004
[    6.784419] hv_pci 9e6a0d4a-8fda-40ae-97cb-94679217f071: PCI host bridge to bus 8fda:00
[    6.788635] pci_bus 8fda:00: root bus resource [mem 0x10010020000-0x1001002bfff window]
[    6.792847] pci_bus 8fda:00: No busn resource found for root bus, will use [bus 00-ff]
[    6.798267] pci 8fda:00:00.0: [1414:b111] type 00 class 0x010802
[    6.802442] pci 8fda:00:00.0: reg 0x10: [mem 0x10010028000-0x1001002bfff 64bit]
[    6.807748] pci 8fda:00:00.0: reg 0x20: [mem 0x10010020000-0x10010027fff 64bit]
[    6.827504] pci_bus 8fda:00: busn_res: [bus 00-ff] end is updated to 00
[    6.830972] pci 8fda:00:00.0: BAR 4: assigned [mem 0x10010020000-0x10010027fff 64bit]
[    6.835587] pci 8fda:00:00.0: BAR 0: assigned [mem 0x10010028000-0x1001002bfff 64bit]
[    6.840493] hv_pci 3809379e-784e-4796-8f19-c8d304b98fb9: PCI VMBus probing: Using version 0x10004
[    6.847604] hv_pci 3809379e-784e-4796-8f19-c8d304b98fb9: PCI host bridge to bus 784e:00
[    6.851842] pci_bus 784e:00: root bus resource [mem 0x10010030000-0x1001003bfff window]
[    6.856087] pci_bus 784e:00: No busn resource found for root bus, will use [bus 00-ff]
[    6.861448] pci 784e:00:00.0: [1414:b111] type 00 class 0x010802
[    6.865677] pci 784e:00:00.0: reg 0x10: [mem 0x10010038000-0x1001003bfff 64bit]
[    6.870833] pci 784e:00:00.0: reg 0x20: [mem 0x10010030000-0x10010037fff 64bit]
[    6.890350] pci_bus 784e:00: busn_res: [bus 00-ff] end is updated to 00
[    6.893836] pci 784e:00:00.0: BAR 4: assigned [mem 0x10010030000-0x10010037fff 64bit]
[    6.898498] pci 784e:00:00.0: BAR 0: assigned [mem 0x10010038000-0x1001003bfff 64bit]
[    6.903387] hv_pci 14056f88-da2b-435b-a15a-a4e7c88d5718: PCI VMBus probing: Using version 0x10004
[    6.911591] hv_pci 14056f88-da2b-435b-a15a-a4e7c88d5718: PCI host bridge to bus da2b:00
[    6.915856] pci_bus da2b:00: root bus resource [mem 0x10010040000-0x1001004bfff window]
[    6.920064] pci_bus da2b:00: No busn resource found for root bus, will use [bus 00-ff]
[    6.925438] pci da2b:00:00.0: [1414:b111] type 00 class 0x010802
[    6.929682] pci da2b:00:00.0: reg 0x10: [mem 0x10010048000-0x1001004bfff 64bit]
[    6.934804] pci da2b:00:00.0: reg 0x20: [mem 0x10010040000-0x10010047fff 64bit]
[    6.954308] pci_bus da2b:00: busn_res: [bus 00-ff] end is updated to 00
[    6.957853] pci da2b:00:00.0: BAR 4: assigned [mem 0x10010040000-0x10010047fff 64bit]
[    6.962435] pci da2b:00:00.0: BAR 0: assigned [mem 0x10010048000-0x1001004bfff 64bit]
[    6.967379] hv_pci 679d2c53-c07d-46b8-b2bc-85a380a6d6db: PCI VMBus probing: Using version 0x10004
[    6.974487] hv_pci 679d2c53-c07d-46b8-b2bc-85a380a6d6db: PCI host bridge to bus c07d:00
[    6.978784] pci_bus c07d:00: root bus resource [mem 0x10010050000-0x1001005bfff window]
[    6.983021] pci_bus c07d:00: No busn resource found for root bus, will use [bus 00-ff]
[    6.988473] pci c07d:00:00.0: [1414:b111] type 00 class 0x010802
[    6.992740] pci c07d:00:00.0: reg 0x10: [mem 0x10010058000-0x1001005bfff 64bit]
[    6.997932] pci c07d:00:00.0: reg 0x20: [mem 0x10010050000-0x10010057fff 64bit]
[    7.017655] pci_bus c07d:00: busn_res: [bus 00-ff] end is updated to 00
[    7.021212] pci c07d:00:00.0: BAR 4: assigned [mem 0x10010050000-0x10010057fff 64bit]
[    7.025872] pci c07d:00:00.0: BAR 0: assigned [mem 0x10010058000-0x1001005bfff 64bit]
[    7.030860] hv_pci 63a2d487-6103-4432-a5e0-9d9904ea52d6: PCI VMBus probing: Using version 0x10004
[    7.038004] hv_pci 63a2d487-6103-4432-a5e0-9d9904ea52d6: PCI host bridge to bus 6103:00
[    7.042376] pci_bus 6103:00: root bus resource [mem 0x10010060000-0x1001006bfff window]
[    7.046508] pci_bus 6103:00: No busn resource found for root bus, will use [bus 00-ff]
[    7.051953] pci 6103:00:00.0: [1414:b111] type 00 class 0x010802
[    7.056158] pci 6103:00:00.0: reg 0x10: [mem 0x10010068000-0x1001006bfff 64bit]
[    7.061590] pci 6103:00:00.0: reg 0x20: [mem 0x10010060000-0x10010067fff 64bit]
[    7.081420] pci_bus 6103:00: busn_res: [bus 00-ff] end is updated to 00
[    7.084902] pci 6103:00:00.0: BAR 4: assigned [mem 0x10010060000-0x10010067fff 64bit]
[    7.089542] pci 6103:00:00.0: BAR 0: assigned [mem 0x10010068000-0x1001006bfff 64bit]
[    7.094556] hv_pci 99e0daa0-68b2-4c34-a8d2-60194790e4dd: PCI VMBus probing: Using version 0x10004
[    7.101709] hv_pci 99e0daa0-68b2-4c34-a8d2-60194790e4dd: PCI host bridge to bus 68b2:00
[    7.105921] pci_bus 68b2:00: root bus resource [mem 0x10010070000-0x1001007bfff window]
[    7.110135] pci_bus 68b2:00: No busn resource found for root bus, will use [bus 00-ff]
[    7.115621] pci 68b2:00:00.0: [1414:b111] type 00 class 0x010802
[    7.119806] pci 68b2:00:00.0: reg 0x10: [mem 0x10010078000-0x1001007bfff 64bit]
[    7.124957] pci 68b2:00:00.0: reg 0x20: [mem 0x10010070000-0x10010077fff 64bit]
[    7.144533] pci_bus 68b2:00: busn_res: [bus 00-ff] end is updated to 00
[    7.148013] pci 68b2:00:00.0: BAR 4: assigned [mem 0x10010070000-0x10010077fff 64bit]
[    7.152679] pci 68b2:00:00.0: BAR 0: assigned [mem 0x10010078000-0x1001007bfff 64bit]
[    7.162488] Serial: 8250/16550 driver, 32 ports, IRQ sharing enabled
[    7.191696] 00:00: ttyS0 at I/O 0x3f8 (irq = 4, base_baud = 115200) is a 16550A
[    7.221402] 00:01: ttyS1 at I/O 0x2f8 (irq = 3, base_baud = 115200) is a 16550A
[    7.227531] Linux agpgart interface v0.103
[    7.257887] loop: module loaded
[    7.259834] hv_vmbus: registering driver hv_storvsc
[    7.263062] nvme nvme0: pci function 0dcc:00:00.0
[    7.266093] nvme 0dcc:00:00.0: enabling device (0404 -> 0406)
[    7.266195] nvme nvme1: pci function 8480:00:00.0
[    7.267907] scsi host0: storvsc_host_t
[    7.268017] scsi host1: storvsc_host_t
[    7.276655] nvme nvme2: pci function 8fda:00:00.0
[    7.277008] nvme 8480:00:00.0: enabling device (0404 -> 0406)
[    7.279623] nvme nvme3: pci function 784e:00:00.0
[    7.279920] nvme 8fda:00:00.0: enabling device (0404 -> 0406)
[    7.289432] nvme nvme4: pci function da2b:00:00.0
[    7.289703] nvme 784e:00:00.0: enabling device (0404 -> 0406)
[    7.292427] nvme nvme5: pci function c07d:00:00.0
[    7.298156] nvme da2b:00:00.0: enabling device (0404 -> 0406)
[    7.298515] nvme c07d:00:00.0: enabling device (0404 -> 0406)
[    7.307130] nvme nvme6: pci function 6103:00:00.0
[    7.310217] nvme nvme7: pci function 68b2:00:00.0
[    7.310947] nvme 6103:00:00.0: enabling device (0404 -> 0406)
[    7.313394] tun: Universal TUN/TAP device driver, 1.6
[    7.313497] nvme 68b2:00:00.0: enabling device (0404 -> 0406)
[    7.324239] PPP generic driver version 2.4.2
[    7.326847] VFIO - User Level meta-driver version: 0.3
[    7.329710] nvme nvme2: Shutdown timeout set to 8 seconds
[    7.330093] i8042: PNP: No PS/2 controller found.
[    7.335149] nvme nvme0: Shutdown timeout set to 8 seconds
[    7.335622] mousedev: PS/2 mouse device common for all mice
[    7.344569] rtc_cmos 00:02: registered as rtc0
[    7.347330] rtc_cmos 00:02: setting system clock to 2025-05-10T20:51:03 UTC (1746910263)
[    7.351210] nvme nvme1: Shutdown timeout set to 8 seconds
[    7.351335] nvme nvme3: Shutdown timeout set to 8 seconds
[    7.352178] rtc_cmos 00:02: alarms up to one month, 114 bytes nvram
[    7.363494] device-mapper: core: CONFIG_IMA_DISABLE_HTABLE is disabled. Duplicate IMA measurements will not be recorded in the IMA log.
[    7.367657] nvme nvme6: Shutdown timeout set to 8 seconds
[    7.367682] nvme nvme5: Shutdown timeout set to 8 seconds
[    7.367708] nvme nvme4: Shutdown timeout set to 8 seconds
[    7.370681] nvme nvme7: Shutdown timeout set to 8 seconds
[    7.370779] device-mapper: uevent: version 1.0.3
[    7.370869] device-mapper: ioctl: 4.45.0-ioctl (2021-03-22) initialised: dm-devel@redhat.com
[    7.370895] platform eisa.0: Probing EISA bus 0
[    7.370922] platform eisa.0: EISA: Detected 0 cards
[    7.370950] EFI Variables Facility v0.08 2004-May-17
[    7.378120] hv_utils: Registering HyperV Utility Driver
[    7.405689] hv_vmbus: registering driver hv_utils
[    7.408793] hv_vmbus: registering driver hv_balloon
[    7.409184] hv_utils: Heartbeat IC version 3.0
[    7.412369] drop_monitor: Initializing network drop monitor service
[    7.415407] hv_utils: Shutdown IC version 3.2
[    7.415899] hv_utils: TimeSync IC version 4.0
[    7.420929] NET: Registered PF_INET6 protocol family
[    7.424126] hv_balloon: Using Dynamic Memory protocol version 2.0
[    7.428922] Segment Routing with IPv6
[    7.436918] In-situ OAM (IOAM) with IPv6
[    7.439507] NET: Registered PF_PACKET protocol family
[    7.442977] Key type dns_resolver registered
[    7.463724] IPI shorthand broadcast: enabled
[    7.466139] sched_clock: Marking stable (7424908567, 41199100)->(7713022800, -246915133)
[    7.478215] registered taskstats version 1
[    7.486391] Loading compiled-in X.509 certificates
[    7.489705] Loaded X.509 cert 'Build time autogenerated kernel key: 98f7424e65905238ecae8c75424c2dccc3a068ec'
[    7.495648] scsi 0:0:0:0: Direct-Access     Msft     Virtual Disk     1.0  PQ: 0 ANSI: 5
[    7.496108] Loaded X.509 cert 'Canonical Ltd. Live Patch Signing: 14df34d1a87cf37625abec039ef2bf521249b969'
[    7.506514] Loaded X.509 cert 'Canonical Ltd. Kernel Module Signing: 88f752e560a1e0737e31163a466ad7b70a850c19'
[    7.513088] blacklist: Loading compiled-in revocation X.509 certificates
[    7.513112] scsi 0:0:0:1: Direct-Access     Msft     Virtual Disk     1.0  PQ: 0 ANSI: 5
[    7.517397] Loaded X.509 cert 'Canonical Ltd. Secure Boot Signing: 61482aa2830d0ab2ad5af10b7250da9033ddcef0'
[    7.527632] Loaded X.509 cert 'Canonical Ltd. Secure Boot Signing (2017): 242ade75ac4a15e50d50c84b0d45ff3eae707a03'
[    7.533475] Loaded X.509 cert 'Canonical Ltd. Secure Boot Signing (ESM 2018): 365188c1d374d6b07c3c8f240f8ef722433d6a8b'
[    7.539153] Loaded X.509 cert 'Canonical Ltd. Secure Boot Signing (2019): c0746fd6c5da3ae827864651ad66ae47fe24b3e8'
[    7.545316] scsi 0:0:0:2: CD-ROM            Msft     Virtual DVD-ROM  1.0  PQ: 0 ANSI: 0
[    7.545316] Loaded X.509 cert 'Canonical Ltd. Secure Boot Signing (2021 v1): a8d54bbb3825cfb94fa13c9f8a594a195c107b8d'
[    7.545336] Loaded X.509 cert 'Canonical Ltd. Secure Boot Signing (2021 v2): 4cf046892d6fd3c9a5b03f98d845f90851dc6a8c'
[    7.561942] Loaded X.509 cert 'Canonical Ltd. Secure Boot Signing (2021 v3): 100437bb6de6e469b581e61cd66bce3ef4ed53af'
[    7.567694] Loaded X.509 cert 'Canonical Ltd. Secure Boot Signing (Ubuntu Core 2019): c1d57b8f6b743f23ee41f4f7ee292f06eecadfb9'
[    7.577580] zswap: loaded using pool lzo/zbud
[    7.596645] Key type .fscrypt registered
[    7.598888] Key type fscrypt-provisioning registered
[    7.602358] Key type encrypted registered
[    7.604870] AppArmor: AppArmor sha1 policy hashing enabled
[    7.608560] integrity: Loading X.509 certificate: UEFI:db
[    7.611619] integrity: Loaded X.509 cert 'Microsoft Windows Production PCA 2011: a92902398e16c49778cd90f99e4f9ae17c55af53'
[    7.618419] integrity: Loading X.509 certificate: UEFI:MokListRT (MOKvar table)
[    7.623261] integrity: Loaded X.509 cert 'Canonical Ltd. Master Certificate Authority: ad91990bc22ab1f517048c23b6655a268e345a63'
[    7.629432] ima: No TPM chip found, activating TPM-bypass!
[    7.632466] Loading compiled-in module X.509 certificates
[    7.635862] Loaded X.509 cert 'Build time autogenerated kernel key: 98f7424e65905238ecae8c75424c2dccc3a068ec'
[    7.641695] ima: Allocated hash algorithm: sha1
[    7.644273] ima: No architecture policies found
[    7.646764] evm: Initialising EVM extended attributes:
[    7.649541] evm: security.selinux
[    7.651344] evm: security.SMACK64
[    7.653691] evm: security.SMACK64EXEC
[    7.655681] evm: security.SMACK64TRANSMUTE
[    7.657941] evm: security.SMACK64MMAP
[    7.659919] evm: security.apparmor
[    7.661750] evm: security.ima
[    7.663724] evm: security.capability
[    7.665716] evm: HMAC attrs: 0x1
[    7.668025] PM:   Magic number: 9:207:902
[    7.670767] hv_pci 0000008e-000b-0003-3130-444500000000: hash matches
[    7.674304] processor cpu50: hash matches
[    7.676594] memory memory337: hash matches
[    7.681107] RAS: Correctable Errors collector initialized.
[    7.684734] clk: Disabling unused clocks
[    7.712942] sd 0:0:0:0: Attached scsi generic sg0 type 0
[    7.713446] sd 0:0:0:0: [sda] 2147483648 512-byte logical blocks: (1.10 TB/1.00 TiB)
[    7.716331] sd 0:0:0:1: Attached scsi generic sg1 type 0
[    7.716802] sd 0:0:0:1: [sdb] 6081740800 512-byte logical blocks: (3.11 TB/2.83 TiB)
[    7.716806] sd 0:0:0:1: [sdb] 4096-byte physical blocks
[    7.716861] sd 0:0:0:1: [sdb] Write Protect is off
[    7.716864] sd 0:0:0:1: [sdb] Mode Sense: 0f 00 10 00
[    7.716962] sd 0:0:0:1: [sdb] Write cache: disabled, read cache: enabled, supports DPO and FUA
[    7.720357] sd 0:0:0:0: [sda] 4096-byte physical blocks
[    7.723717] sr 0:0:0:2: [sr0] scsi-1 drive
[    7.724054]  sdb: sdb1
[    7.724707] sd 0:0:0:1: [sdb] Attached SCSI disk
[    7.727706] sd 0:0:0:0: [sda] Write Protect is off
[    7.730492] cdrom: Uniform CD-ROM driver Revision: 3.20
[    7.733349] sd 0:0:0:0: [sda] Mode Sense: 0f 00 10 00
[    7.742824] sr 0:0:0:2: Attached scsi CD-ROM sr0
[    7.743136] sd 0:0:0:0: [sda] Write cache: disabled, read cache: enabled, supports DPO and FUA
[    7.744482] sr 0:0:0:2: Attached scsi generic sg2 type 5
[    7.752854] GPT:Primary header thinks Alt. header is not at the end of the disk.
[    7.764464] GPT:62916607 != 2147483647
[    7.766443] GPT:Alternate GPT header not at the end of the disk.
[    7.769651] GPT:62916607 != 2147483647
[    7.771702] GPT: Use GNU Parted to correct GPT errors.
[    7.774709]  sda: sda1 sda14 sda15
[    7.777392] sd 0:0:0:0: [sda] Attached SCSI disk
[    8.178267] nvme nvme7: 32/0/0 default/read/poll queues
[    8.194842] nvme nvme5: 32/0/0 default/read/poll queues
[    8.217045] nvme nvme3: 32/0/0 default/read/poll queues
[    8.226908] nvme nvme2: 32/0/0 default/read/poll queues
[    8.257397] nvme nvme0: 32/0/0 default/read/poll queues
[    8.257505] nvme nvme1: 32/0/0 default/read/poll queues
[    8.258293] nvme nvme6: 32/0/0 default/read/poll queues
[    8.321913] nvme nvme4: 32/0/0 default/read/poll queues
[    8.370877] md: Waiting for all devices to be available before autodetect
[    8.374661] md: If you don't use raid, use raid=noautodetect
[    8.377839] md: Autodetecting RAID arrays.
[    8.380091] md: autorun ...
[    8.381763] md: ... autorun DONE.
[    8.385448] EXT4-fs (sda1): mounted filesystem with ordered data mode. Opts: (null). Quota mode: none.
[    8.390524] VFS: Mounted root (ext4 filesystem) readonly on device 8:1.
[    8.394178] devtmpfs: mounted
[    8.399267] Freeing unused decrypted memory: 2036K
[    8.403094] Freeing unused kernel image (initmem) memory: 3100K
[    8.406234] Write protecting the kernel read-only data: 30720k
[    8.410931] Freeing unused kernel image (text/rodata gap) memory: 2036K
[    8.415250] Freeing unused kernel image (rodata/data gap) memory: 1756K
[    8.507509] x86/mm: Checked W+X mappings: passed, no W+X pages found.
[    8.511147] Run /sbin/init as init process
[    8.513358]   with arguments:
[    8.513360]     /sbin/init
[    8.513361]   with environment:
[    8.513363]     HOME=/
[    8.513364]     TERM=linux
[    8.513365]     BOOT_IMAGE=/boot/vmlinuz-5.15.0-1087-azure
[    8.552784] systemd[1]: Inserted module 'autofs4'
[    8.574059] systemd[1]: systemd 249.11-0ubuntu3.15 running in system mode (+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
[    8.609298] systemd[1]: Detected virtualization microsoft.
[    8.612380] systemd[1]: Detected architecture x86-64.
[    8.617450] systemd[1]: Hostname set to <localhost.localdomain>.
[    8.621474] systemd[1]: Initializing machine ID from random generator.
[    8.625136] systemd[1]: Installed transient /etc/machine-id file.
[    8.769612] systemd[1]: Configuration file /run/systemd/system/netplan-ovs-cleanup.service is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.
[    8.796570] systemd[1]: Configuration file /etc/systemd/system/sync-container-logs.service is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.
[    8.811408] systemd[1]: Configuration file /etc/systemd/system/kubelet.service is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.
[    8.857229] systemd[1]: Queued start job for default target Graphical Interface.
[    8.861343] systemd[1]: Unnecessary job was removed for /sys/devices/virtual/misc/vmbus!hv_fcopy.
[    8.866179] systemd[1]: Unnecessary job was removed for /sys/devices/virtual/misc/vmbus!hv_vss.
[    8.875164] systemd[1]: Created slice Slice /system/modprobe.
[    8.881478] systemd[1]: Created slice Slice /system/serial-getty.
[    8.888176] systemd[1]: Created slice Slice /system/systemd-fsck.
[    8.894807] systemd[1]: Created slice User and Session Slice.
[    8.900347] systemd[1]: Started Forward Password Requests to Wall Directory Watch.
[    8.907605] systemd[1]: Set up automount Arbitrary Executable File Formats File System Automount Point.
[    8.916050] systemd[1]: Reached target ceph target allowing to start/stop all ceph*@.service instances at once.
[    8.924592] systemd[1]: Reached target Slice Units.
[    8.929284] systemd[1]: Reached target Swaps.
[    8.933592] systemd[1]: Reached target System Time Set.
[    8.938719] systemd[1]: Reached target Local Verity Protected Volumes.
[    8.945051] systemd[1]: Listening on Device-mapper event daemon FIFOs.
[    8.951280] systemd[1]: Listening on LVM2 poll daemon socket.
[    8.956862] systemd[1]: Listening on multipathd control socket.
[    8.962689] systemd[1]: Listening on Syslog Socket.
[    8.967398] systemd[1]: Listening on fsck to fsckd communication Socket.
[    8.973760] systemd[1]: Listening on initctl Compatibility Named Pipe.
[    8.980121] systemd[1]: Listening on Journal Audit Socket.
[    8.985435] systemd[1]: Listening on Journal Socket (/dev/log).
[    8.991071] systemd[1]: Listening on Journal Socket.
[    8.995935] systemd[1]: Listening on Network Service Netlink Socket.
[    9.001962] systemd[1]: Listening on udev Control Socket.
[    9.007133] systemd[1]: Listening on udev Kernel Socket.
[    9.013546] systemd[1]: Mounting Huge Pages File System...
[    9.019831] systemd[1]: Mounting POSIX Message Queue File System...
[    9.026655] systemd[1]: Mounting Kernel Debug File System...
[    9.032977] systemd[1]: Mounting Kernel Trace File System...
[    9.043368] systemd[1]: Starting Journal Service...
[    9.048049] systemd[1]: Condition check resulted in Kernel Module supporting RPCSEC_GSS being skipped.
[    9.054642] systemd[1]: Starting Set the console keyboard layout...
[    9.062224] systemd[1]: Starting Create List of Static Device Nodes...
[    9.069394] systemd[1]: Starting Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling...
[    9.077714] systemd[1]: Condition check resulted in LXD - agent being skipped.
[    9.082915] systemd[1]: Starting Load Kernel Module configfs...
[    9.089447] systemd[1]: Starting Load Kernel Module drm...
[    9.095792] systemd[1]: Starting Load Kernel Module efi_pstore...
[    9.102458] systemd[1]: Starting Load Kernel Module fuse...
[    9.107624] systemd[1]: Condition check resulted in OpenVSwitch configuration for cleanup being skipped.
[    9.114511] systemd[1]: Starting File System Check on Root Device...
[    9.118540] pstore: Using crash dump compression: deflate
[    9.122148] pstore: Registered efi as persistent store backend
[    9.127924] systemd[1]: Starting Load Kernel Modules...
[    9.134115] systemd[1]: Starting Coldplug All udev Devices...
[    9.141129] systemd[1]: Mounted Huge Pages File System.
[    9.146417] systemd[1]: Mounted POSIX Message Queue File System.
[    9.152168] systemd[1]: Mounted Kernel Debug File System.
[    9.157475] systemd[1]: Mounted Kernel Trace File System.
[    9.163119] systemd[1]: Finished Set the console keyboard layout.
[    9.169574] systemd[1]: Finished Create List of Static Device Nodes.
[    9.175849] systemd[1]: modprobe@configfs.service: Deactivated successfully.
[    9.179889] systemd[1]: Finished Load Kernel Module configfs.
[    9.185408] systemd[1]: Started Journal Service.
[    9.287470] EXT4-fs (sda1): re-mounted. Opts: discard,errors=remount-ro. Quota mode: none.
[    9.300695] alua: device handler registered
[    9.301073] systemd-journald[870]: Received client request to flush runtime journal.
[    9.303960] emc: device handler registered
[    9.307767] rdac: device handler registered
[    9.426118] hv_vmbus: registering driver hyperv_fb
[    9.427108] hyperv_fb: Synthvid Version major 3, minor 5
[    9.427152] hyperv_fb: Screen resolution: 1024x768, Color depth: 32, Frame buffer size: 8388608
[    9.429760] hv_vmbus: registering driver hyperv_keyboard
[    9.433975] Console: switching to colour frame buffer device 128x48
[    9.437321] hv_vmbus: registering driver hv_netvsc
[    9.437777] hid: raw HID events driver (C) Jiri Kosina
[    9.438958] input: AT Translated Set 2 keyboard as /devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0004:00/VMBUS:00/d34b2567-b9b6-42b9-8778-0a4ec0b955bf/serio0/input/input0
[    9.443031] hv_vmbus: registering driver hid_hyperv
[    9.448344] input: Microsoft Vmbus HID-compliant Mouse as /devices/0006:045E:0621.0001/input/input1
[    9.451142] hid 0006:045E:0621.0001: input: VIRTUAL HID v0.01 Mouse [Microsoft Vmbus HID-compliant Mouse] on
[    9.515103] cryptd: max_cpu_qlen set to 1000
[    9.519440] hv_vmbus: registering driver hyperv_drm
[    9.550057] AVX2 version of gcm_enc/dec engaged.
[    9.551747] AES CTR mode by8 optimization enabled
[    9.704076] hv_utils: KVP IC version 4.0
[    9.919791] audit: type=1400 audit(1746910266.466:2): apparmor="STATUS" operation="profile_load" profile="unconfined" name="lsb_release" pid=1398 comm="apparmor_parser"
[    9.920286] audit: type=1400 audit(1746910266.466:3): apparmor="STATUS" operation="profile_load" profile="unconfined" name="nvidia_modprobe" pid=1399 comm="apparmor_parser"
[    9.920292] audit: type=1400 audit(1746910266.466:4): apparmor="STATUS" operation="profile_load" profile="unconfined" name="nvidia_modprobe//kmod" pid=1399 comm="apparmor_parser"
[    9.920377] audit: type=1400 audit(1746910266.466:5): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/usr/bin/man" pid=1404 comm="apparmor_parser"
[    9.920383] audit: type=1400 audit(1746910266.466:6): apparmor="STATUS" operation="profile_load" profile="unconfined" name="man_filter" pid=1404 comm="apparmor_parser"
[    9.920388] audit: type=1400 audit(1746910266.466:7): apparmor="STATUS" operation="profile_load" profile="unconfined" name="man_groff" pid=1404 comm="apparmor_parser"
[    9.921707] audit: type=1400 audit(1746910266.470:8): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/usr/sbin/chronyd" pid=1406 comm="apparmor_parser"
[    9.922709] audit: type=1400 audit(1746910266.470:9): apparmor="STATUS" operation="profile_load" profile="unconfined" name="ubuntu_pro_apt_news" pid=1402 comm="apparmor_parser"
[    9.925350] audit: type=1400 audit(1746910266.474:10): apparmor="STATUS" operation="profile_load" profile="unconfined" name="tcpdump" pid=1405 comm="apparmor_parser"
[    9.927211] audit: type=1400 audit(1746910266.474:11): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/usr/lib/NetworkManager/nm-dhcp-client.action" pid=1400 comm="apparmor_parser"
[   10.059330] UDF-fs: INFO Mounting volume 'UDF Volume', timestamp 2025/05/11 00:00 (1000)
[   10.099092] hv_netvsc 6045bde4-75d2-6045-bde4-75d26045bde4 eth0: VF slot 1 added
[   10.100260] RPC: Registered named UNIX socket transport module.
[   10.100264] RPC: Registered udp transport module.
[   10.100265] RPC: Registered tcp transport module.
[   10.100267] RPC: Registered tcp NFSv4.1 backchannel transport module.
[   10.100600] hv_pci e144e523-6cfd-4ebc-8a3e-991599568c42: PCI VMBus probing: Using version 0x10004
[   10.101910] hv_pci e144e523-6cfd-4ebc-8a3e-991599568c42: PCI host bridge to bus 6cfd:00
[   10.101914] pci_bus 6cfd:00: root bus resource [mem 0x10010100000-0x100101fffff window]
[   10.101918] pci_bus 6cfd:00: No busn resource found for root bus, will use [bus 00-ff]
[   10.103638] pci 6cfd:00:02.0: [15b3:1016] type 00 class 0x020000
[   10.106117] pci 6cfd:00:02.0: reg 0x10: [mem 0x10010100000-0x100101fffff 64bit pref]
[   10.108238] pci 6cfd:00:02.0: enabling Extended Tags
[   10.116267] pci 6cfd:00:02.0: 0.000 Gb/s available PCIe bandwidth, limited by Unknown x0 link at 6cfd:00:02.0 (capable of 63.008 Gb/s with 8.0 GT/s PCIe x8 link)
[   10.122567] pci_bus 6cfd:00: busn_res: [bus 00-ff] end is updated to 00
[   10.122576] pci 6cfd:00:02.0: BAR 0: assigned [mem 0x10010100000-0x100101fffff 64bit pref]
[   10.250173] mlx5_core 0101:00:00.0: enabling device (0000 -> 0002)
[   10.253283] mlx5_core 0101:00:00.0: firmware version: 20.31.1754
[   10.430501] mlx5_core 0102:00:00.0: enabling device (0000 -> 0002)
[   10.433236] mlx5_core 0102:00:00.0: firmware version: 20.31.1754
[   10.610096] mlx5_core 0103:00:00.0: enabling device (0000 -> 0002)
[   10.612797] mlx5_core 0103:00:00.0: firmware version: 20.31.1754
[   10.796940] mlx5_core 0104:00:00.0: enabling device (0000 -> 0002)
[   10.799569] mlx5_core 0104:00:00.0: firmware version: 20.31.1754
[   10.978316] mlx5_core 0105:00:00.0: enabling device (0000 -> 0002)
[   10.981134] mlx5_core 0105:00:00.0: firmware version: 20.31.1754
[   11.162658] mlx5_core 0106:00:00.0: enabling device (0000 -> 0002)
[   11.165306] mlx5_core 0106:00:00.0: firmware version: 20.31.1754
[   11.354141] mlx5_core 0107:00:00.0: enabling device (0000 -> 0002)
[   11.356979] mlx5_core 0107:00:00.0: firmware version: 20.31.1754
[   11.536935] mlx5_core 0108:00:00.0: enabling device (0000 -> 0002)
[   11.539653] mlx5_core 0108:00:00.0: firmware version: 20.31.1754
[   11.720190] mlx5_core 6cfd:00:02.0: enabling device (0000 -> 0002)
[   11.723137] mlx5_core 6cfd:00:02.0: firmware version: 14.30.5000
[   11.903795] mlx5_core 6cfd:00:02.0: MLX5E: StrdRq(0) RqSz(1024) StrdSz(256) RxCqeCmprss(0)
[   12.000015] mlx5_core 6cfd:00:02.0: Supported tc offload range - chains: 1, prios: 1
[   12.000020] mlx5_core 6cfd:00:02.0: mlx5e_tc_post_act_init:40:(pid 500): firmware level support is missing
[   12.000023] mlx5_core 6cfd:00:02.0: mlx5_tc_ct_init:2088:(pid 500): tc ct offload not supported, tc ct offload not supported, post action is missing
[   12.002634] hv_netvsc 6045bde4-75d2-6045-bde4-75d26045bde4 eth0: VF registering: eth1
[   12.002703] mlx5_core 6cfd:00:02.0 eth1: joined to eth0
[   12.015731] mlx5_core 6cfd:00:02.0 enP27901s1: renamed from eth1
[   12.733287] mlx5_core 6cfd:00:02.0 enP27901s1: Link up
[   12.774686] hv_netvsc 6045bde4-75d2-6045-bde4-75d26045bde4 eth0: Data path switched to VF: enP27901s1
[   12.776094] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   12.819118] IPv4: martian source 255.255.255.255 from 168.63.129.16, on dev eth0
[   12.819148] ll header: 00000000: 60 45 bd e4 75 d2 12 34 56 78 9a bc 08 00
[   12.824062] IPv4: martian source 255.255.255.255 from 168.63.129.16, on dev eth0
[   12.824075] ll header: 00000000: 60 45 bd e4 75 d2 12 34 56 78 9a bc 08 00
[   13.221738] hv_netvsc 6045bde4-75d2-6045-bde4-75d26045bde4 eth0: Data path switched from VF: enP27901s1
[   13.996299] mlx5_core 6cfd:00:02.0 enP27901s1: Link up
[   14.022860] hv_netvsc 6045bde4-75d2-6045-bde4-75d26045bde4 eth0: Data path switched to VF: enP27901s1
[   14.048209] IPv4: martian source 255.255.255.255 from 168.63.129.16, on dev eth0
[   14.048237] ll header: 00000000: 60 45 bd e4 75 d2 12 34 56 78 9a bc 08 00
[   14.051142] IPv4: martian source 255.255.255.255 from 168.63.129.16, on dev eth0
[   14.051156] ll header: 00000000: 60 45 bd e4 75 d2 12 34 56 78 9a bc 08 00
[   16.615800] hv_storvsc f8b3781a-1e82-4818-a1c3-63d806ec15bb: tag#2145 cmd 0x28 status: scsi 0x2 srb 0x84 hv 0xc0000001
[   16.615831] sr 0:0:0:2: [sr0] tag#2145 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_OK cmd_age=0s
[   16.615841] sr 0:0:0:2: [sr0] tag#2145 Sense Key : Not Ready [current]
[   16.615850] sr 0:0:0:2: [sr0] tag#2145 Add. Sense: Medium not present - tray open
[   16.615859] sr 0:0:0:2: [sr0] tag#2145 CDB: Read(10) 28 00 00 00 00 02 00 00 02 00
[   16.615865] blk_update_request: I/O error, dev sr0, sector 8 op 0x0:(READ) flags 0x80700 phys_seg 1 prio class 0
[   16.621410] hv_storvsc f8b3781a-1e82-4818-a1c3-63d806ec15bb: tag#2146 cmd 0x28 status: scsi 0x2 srb 0x84 hv 0xc0000001
[   16.621424] sr 0:0:0:2: [sr0] tag#2146 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_OK cmd_age=0s
[   16.621432] sr 0:0:0:2: [sr0] tag#2146 Sense Key : Not Ready [current]
[   16.621440] sr 0:0:0:2: [sr0] tag#2146 Add. Sense: Medium not present - tray open
[   16.621447] sr 0:0:0:2: [sr0] tag#2146 CDB: Read(10) 28 00 00 00 00 02 00 00 01 00
[   16.621453] blk_update_request: I/O error, dev sr0, sector 8 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[   16.626757] Buffer I/O error on dev sr0, logical block 2, async page read
[   16.630340] hv_storvsc f8b3781a-1e82-4818-a1c3-63d806ec15bb: tag#2147 cmd 0x28 status: scsi 0x2 srb 0x84 hv 0xc0000001
[   16.630350] sr 0:0:0:2: [sr0] tag#2147 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_OK cmd_age=0s
[   16.630358] sr 0:0:0:2: [sr0] tag#2147 Sense Key : Not Ready [current]
[   16.630365] sr 0:0:0:2: [sr0] tag#2147 Add. Sense: Medium not present - tray open
[   16.630372] sr 0:0:0:2: [sr0] tag#2147 CDB: Read(10) 28 00 00 00 00 03 00 00 01 00
[   16.630378] blk_update_request: I/O error, dev sr0, sector 12 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[   16.635620] Buffer I/O error on dev sr0, logical block 3, async page read
[   17.507538] EXT4-fs (sda1): resizing filesystem from 7836155 to 268407035 blocks
[   27.539836] EXT4-fs (sda1): resized to 83361792 blocks
[   37.594985] EXT4-fs (sda1): resized to 152567808 blocks
[   47.636390] EXT4-fs (sda1): resized to 222298112 blocks
[   54.193933] EXT4-fs (sda1): resized filesystem to 268407035
[   54.235742]  sdb: sdb1
[   55.021622] EXT4-fs (sdb1): mounted filesystem with ordered data mode. Opts: (null). Quota mode: none.
[   55.525926] hv_balloon: Max. dynamic memory size: 921600 MB
[   67.640048] bridge: filtering via arp/ip/ip6tables is no longer available by default. Update your scripts to load br_netfilter if you need this.
[   67.660496] Bridge firewalling registered
[   80.434822] kauditd_printk_skb: 14 callbacks suppressed
[   80.434826] audit: type=1400 audit(1746910336.981:26): apparmor="STATUS" operation="profile_load" profile="unconfined" name="cri-containerd.apparmor.d" pid=5713 comm="apparmor_parser"
[  131.935691] IPv6: ADDRCONF(NETDEV_CHANGE): azv8c04e4115cc2: link becomes ready
[  131.935979] IPv6: ADDRCONF(NETDEV_CHANGE): azv8c04e4115cc: link becomes ready
[  131.937514] eth0: renamed from azv8c04e4115cc2
[  139.839819] IPv6: ADDRCONF(NETDEV_CHANGE): azv64532457ee52: link becomes ready
[  139.840036] IPv6: ADDRCONF(NETDEV_CHANGE): azv64532457ee5: link becomes ready
[  139.841603] eth0: renamed from azv64532457ee52
[  145.843760] IPv6: ADDRCONF(NETDEV_CHANGE): azvf4cadcda5a02: link becomes ready
[  145.843993] IPv6: ADDRCONF(NETDEV_CHANGE): azvf4cadcda5a0: link becomes ready
[  145.846964] eth0: renamed from azvf4cadcda5a02
[  146.011771] IPv6: ADDRCONF(NETDEV_CHANGE): azv73b709f3dd6: link becomes ready
[  146.013092] eth0: renamed from azv73b709f3dd62
[  146.251617] IPv6: ADDRCONF(NETDEV_CHANGE): azva6b6ef9ca29: link becomes ready
[  146.252528] eth0: renamed from azva6b6ef9ca292
[  146.384155] IPv6: ADDRCONF(NETDEV_CHANGE): azvf19668363ba: link becomes ready
[  146.385311] eth0: renamed from azvf19668363ba2
[  395.287406] hv_netvsc 6045bde4-75d2-6045-bde4-75d26045bde4 eth0: Data path switched from VF: enP27901s1
[  395.432817] hv_netvsc 6045bde4-75d2-6045-bde4-75d26045bde4 eth0: VF unregistering: enP27901s1
[  409.231012] mlx_compat: loading out-of-tree module taints kernel.
[  409.231071] mlx_compat: module verification failed: signature and/or required key missing - tainting kernel
[  409.233104] Compat-mlnx-ofed backport release: f5ad9dd
[  409.233106] Backport based on https://:@git-nbu.nvidia.com/r/a/mlnx_ofed/mlnx-ofa_kernel-4.0.git f5ad9dd
[  409.233107] compat.git: https://:@git-nbu.nvidia.com/r/a/mlnx_ofed/mlnx-ofa_kernel-4.0.git
[  409.310649] mlx5_core 0101:00:00.0: firmware version: 20.31.1754
[  409.479396] mlx5_core 0102:00:00.0: firmware version: 20.31.1754
[  409.645199] mlx5_core 0103:00:00.0: firmware version: 20.31.1754
[  409.811378] mlx5_core 0104:00:00.0: firmware version: 20.31.1754
[  409.981063] mlx5_core 0105:00:00.0: firmware version: 20.31.1754
[  410.147516] mlx5_core 0106:00:00.0: firmware version: 20.31.1754
[  410.313265] mlx5_core 0107:00:00.0: firmware version: 20.31.1754
[  410.483439] mlx5_core 0108:00:00.0: firmware version: 20.31.1754
[  410.652238] mlx5_core 6cfd:00:02.0: firmware version: 14.30.5000
[  410.815981] mlx5_core 6cfd:00:02.0: MLX5E: StrdRq(0) RqSz(1024) StrdSz(256) RxCqeCmprss(0 basic)
[  410.901688] hv_netvsc 6045bde4-75d2-6045-bde4-75d26045bde4 eth0: VF registering: eth1
[  410.901782] mlx5_core 6cfd:00:02.0 eth1: joined to eth0
[  410.917574] mlx5_core 6cfd:00:02.0 enP27901s1: renamed from eth1
[  411.746966] mlx5_core 6cfd:00:02.0 enP27901s1: Link up
[  411.778790] hv_netvsc 6045bde4-75d2-6045-bde4-75d26045bde4 eth0: Data path switched to VF: enP27901s1
[  411.897642] mlx5_core 0101:00:00.0: MLX5E: StrdRq(0) RqSz(1024) StrdSz(256) RxCqeCmprss(0 basic)
[  411.897721] mlx5_core 0101:00:00.0: MLX5E: StrdRq(0) RqSz(1024) StrdSz(256) RxCqeCmprss(0 basic)
[  411.930537] mlx5_core 0102:00:00.0: MLX5E: StrdRq(0) RqSz(1024) StrdSz(256) RxCqeCmprss(0 basic)
[  411.930612] mlx5_core 0102:00:00.0: MLX5E: StrdRq(0) RqSz(1024) StrdSz(256) RxCqeCmprss(0 basic)
[  411.939966] mlx5_core 0101:00:00.0 ibP257s154057: renamed from ib0
[  411.963082] mlx5_core 0103:00:00.0: MLX5E: StrdRq(0) RqSz(1024) StrdSz(256) RxCqeCmprss(0 basic)
[  411.963154] mlx5_core 0103:00:00.0: MLX5E: StrdRq(0) RqSz(1024) StrdSz(256) RxCqeCmprss(0 basic)
[  411.973391] mlx5_core 0102:00:00.0 ibP258s154115: renamed from ib0
[  412.014653] mlx5_core 0104:00:00.0: MLX5E: StrdRq(0) RqSz(1024) StrdSz(256) RxCqeCmprss(0 basic)
[  412.014753] mlx5_core 0104:00:00.0: MLX5E: StrdRq(0) RqSz(1024) StrdSz(256) RxCqeCmprss(0 basic)
[  412.023404] mlx5_core 0103:00:00.0 ibP259s154060: renamed from ib0
[  412.058789] mlx5_core 0105:00:00.0: MLX5E: StrdRq(0) RqSz(1024) StrdSz(256) RxCqeCmprss(0 basic)
[  412.058864] mlx5_core 0105:00:00.0: MLX5E: StrdRq(0) RqSz(1024) StrdSz(256) RxCqeCmprss(0 basic)
[  412.068565] mlx5_core 0104:00:00.0 ibP260s154056: renamed from ib0
[  412.102850] mlx5_core 0106:00:00.0: MLX5E: StrdRq(0) RqSz(1024) StrdSz(256) RxCqeCmprss(0 basic)
[  412.102985] mlx5_core 0106:00:00.0: MLX5E: StrdRq(0) RqSz(1024) StrdSz(256) RxCqeCmprss(0 basic)
[  412.112350] mlx5_core 0105:00:00.0 ibP261s154347: renamed from ib0
[  412.170969] mlx5_core 0107:00:00.0: MLX5E: StrdRq(0) RqSz(1024) StrdSz(256) RxCqeCmprss(0 basic)
[  412.171044] mlx5_core 0107:00:00.0: MLX5E: StrdRq(0) RqSz(1024) StrdSz(256) RxCqeCmprss(0 basic)
[  412.180241] mlx5_core 0106:00:00.0 ibP262s154407: renamed from ib0
[  412.218753] mlx5_core 0108:00:00.0: MLX5E: StrdRq(0) RqSz(1024) StrdSz(256) RxCqeCmprss(0 basic)
[  412.218825] mlx5_core 0108:00:00.0: MLX5E: StrdRq(0) RqSz(1024) StrdSz(256) RxCqeCmprss(0 basic)
[  412.227766] mlx5_core 0107:00:00.0 ibP263s154129: renamed from ib0
[  412.272249] mlx5_core 0108:00:00.0 ibP264s154156: renamed from ib0
[  517.982623] infiniband mlx5_8: create_qp:3317:(pid 57806): Create QP type 2 failed
[  714.742308] IPv6: ADDRCONF(NETDEV_CHANGE): azv3fa7f0617db2: link becomes ready
[  714.742540] IPv6: ADDRCONF(NETDEV_CHANGE): azv3fa7f0617db: link becomes ready
[  714.745107] eth0: renamed from azv3fa7f0617db2
[ 1507.157418] IPv6: ADDRCONF(NETDEV_CHANGE): azv4e60a95dd922: link becomes ready
[ 1507.157644] IPv6: ADDRCONF(NETDEV_CHANGE): azv4e60a95dd92: link becomes ready
[ 1507.160021] eth0: renamed from azv4e60a95dd922
[ 1507.314023] IPv6: ADDRCONF(NETDEV_CHANGE): azv4d856e1a220: link becomes ready
[ 1507.316008] eth0: renamed from azv4d856e1a2202

